export const firstGrade = [
    { character: '小', unicode: '5C0F', pinyin: 'xiaoˇ', phrase: '小狗', sentence: '小狗很可愛。', image: 'xiao_gou.jpg', translation: 'Small' },
    { character: '羊', unicode: '7F8A', pinyin: 'yangˊ', phrase: '小羊', sentence: '小羊在吃草。', image: 'xiao_yang.jpg', translation: 'Sheep' },
    { character: '草', unicode: '8349', pinyin: 'caoˇ', phrase: '草地', sentence: '他在草地上玩。', image: 'cao_di.jpg', translation: 'Grass' },
    { character: '吃', unicode: '5403', pinyin: 'chi¯', phrase: '吃飯', sentence: '他在吃飯。', image: 'chi_fan.jpg', translation: 'Eat' },
    { character: '天', unicode: '5929', pinyin: 'tian¯', phrase: '天空', sentence: '天空很藍。', image: 'tian_kong.jpg', translation: 'Sky' },
    { character: '少', unicode: '5C11', pinyin: 'shaoˋ', phrase: '少年', sentence: '他是一個少年。', image: 'shao_nian.jpg', translation: 'Young' },
    { character: '高', unicode: '9AD8', pinyin: 'gao¯', phrase: '高山', sentence: '我們登上了高山。', image: 'gao_shan.jpg', translation: 'High' },
    { character: '出', unicode: '51FA', pinyin: 'chu¯', phrase: '出去', sentence: '他出去了。', image: 'chu_qu.jpg', translation: 'Go out' },
    { character: '門', unicode: '95E8', pinyin: 'menˊ', phrase: '門口', sentence: '我站在門口。', image: 'men_kou.jpg', translation: 'Door' },
    { character: '去', unicode: '53BB', pinyin: 'quˋ', phrase: '去年', sentence: '去年我去了中國。', image: 'qu_nian.jpg', translation: 'Go' },
    { character: '開', unicode: '5F00', pinyin: 'kai¯', phrase: '開心', sentence: '他很開心。', image: 'kai_xin.jpg', translation: 'Happy' },
    { character: '心', unicode: '5FC3', pinyin: 'xin¯', phrase: '心情', sentence: '我現在的心情很好。', image: 'xin_qing.jpg', translation: 'Heart' },
    { character: '走', unicode: '8D70', pinyin: 'zouˇ', phrase: '走路', sentence: '我喜歡走路。', image: 'zou_lu.jpg', translation: 'Walk' },
    { character: '路', unicode: '8DEF', pinyin: 'luˋ', phrase: '回家路上', sentence: '我們在回家路上。', image: 'hui_jia_lu_shang.jpg', translation: 'Road' },
    { character: '花', unicode: '82B1', pinyin: 'hua¯', phrase: '花園', sentence: '這是一個美麗的花園。', image: 'hua_yuan.jpg', translation: 'Flower' },
    { character: '田', unicode: '7530', pinyin: 'tianˊ', phrase: '農田', sentence: '我們來到了一片農田。', image: 'nong_tian.jpg', translation: 'Field' },
    { character: '看', unicode: '770B', pinyin: 'kanˋ', phrase: '看電影', sentence: '我們今天去看電影。', image: 'kan_dian_ying.jpg', translation: 'Watch' },
    { character: '見', unicode: '89C1', pinyin: 'jianˋ', phrase: '見面', sentence: '我們明天見面。', image: 'jian_mian.jpg', translation: 'Meet' },
    { character: '白', unicode: '767D', pinyin: 'baiˊ', phrase: '白雪', sentence: '外面下著白雪。', image: 'bai_xue.jpg', translation: 'White' },
    { character: '和', unicode: '548C', pinyin: 'heˊ', phrase: '和平', sentence: '我們追求和平。', image: 'he_ping.jpg', translation: 'Peace' },
    { character: '起', unicode: '8D77', pinyin: 'qiˇ', phrase: '起床', sentence: '他早上八點起床。', image: 'qi_chuang.jpg', translation: 'Get up' },
    { character: '奶', unicode: '5976', pinyin: 'naiˇ', phrase: '奶媽', sentence: '她是我的奶媽。', image: 'nai_ma.jpg', translation: 'Milk' },
    { character: '家', unicode: '5BB6', pinyin: 'jia¯', phrase: '家庭', sentence: '我們是一個幸福的家庭。', image: 'jia_ting.jpg', translation: 'Family' },
    { character: '過', unicode: '8FC7', pinyin: 'guoˋ', phrase: '過去', sentence: '過去的事情就讓它過去吧。', image: 'guo_qu.jpg', translation: 'Past' },
    { character: '兔', unicode: '5154', pinyin: 'tuˋ', phrase: '小兔子', sentence: '小兔子在跳躍。', image: 'xiao_tu_zi.jpg', translation: 'Rabbit' },
    { character: '在', unicode: '5728', pinyin: 'zaiˋ', phrase: '在學校', sentence: '他現在在學校。', image: 'zai_xue_xiao.jpg', translation: 'At' },
    { character: '了', unicode: '4E86', pinyin: 'le˙', phrase: '好了', sentence: '我洗好澡了!', image: 'liao_jie.jpg', translation: 'Used at the end of a sentence' },
    { character: '好', unicode: '597D', pinyin: 'haoˇ', phrase: '好朋友', sentence: '他是我的好朋友。', image: 'hao_peng_you.jpg', translation: 'Good' },
    { character: '多', unicode: '591A', pinyin: 'duo¯', phrase: '多雲', sentence: '今天是一個多雲的天氣。', image: 'duo_yun.jpg', translation: 'Many' },
    { character: '長', unicode: '957F', pinyin: 'zhangˇ', phrase: '長大', sentence: '他希望長大後成為一名醫生。', image: 'zhang_da.jpg', translation: 'Grow up' },
    { character: '要', unicode: '8981', pinyin: 'yaoˋ', phrase: '我要', sentence: '我要買東西。', image: 'yao_qiu.jpg', translation: 'Want' },
    { character: '水', unicode: '6C34', pinyin: 'shuiˇ', phrase: '水果', sentence: '我喜歡吃各種各樣的水果。', image: 'shui_guo.jpg', translation: 'Water' },
    { character: '光', unicode: '5149', pinyin: 'guang¯', phrase: '光明', sentence: '光明將會戰勝黑暗。', image: 'guang_ming.jpg', translation: 'Light' },
    { character: '玩', unicode: '73A9', pinyin: 'wanˊ', phrase: '玩具', sentence: '他在玩具店買了一個玩具。', image: 'wan_ju.jpg', translation: 'Play' },
    { character: '種', unicode: '79CD', pinyin: 'zhongˇ', phrase: '種子', sentence: '種子發芽了。', image: 'zhong_zi.jpg', translation: 'Kind' },
    { character: '喝', unicode: '559D', pinyin: 'he¯', phrase: '喝水', sentence: '他喝了一杯水。', image: 'he_shui.jpg', translation: 'Drink' },
    { character: '陽', unicode: '9633', pinyin: 'yangˊ', phrase: '陽光', sentence: '陽光明媚。', image: 'yang_guang.jpg', translation: 'Sunshine' },
    { character: '請', unicode: '8BF7', pinyin: 'qingˇ', phrase: '請坐', sentence: '請坐，不要客氣。', image: 'qing_zuo.jpg', translation: 'Please' },
    { character: '問', unicode: '95EE', pinyin: 'wenˋ', phrase: '問題', sentence: '你有什麼問題嗎？', image: 'wen_ti.jpg', translation: 'Ask' },
    { character: '你', unicode: '4F60', pinyin: 'niˇ', phrase: '你好', sentence: '你好，我是小明。', image: 'ni_hao.jpg', translation: 'You' },
    { character: '有', unicode: '6709', pinyin: 'youˇ', phrase: '有沒有', sentence: '你有沒有看到我的筆？', image: 'you_mei_you.jpg', translation: 'Have' },
    { character: '星', unicode: '661F', pinyin: 'xing¯', phrase: '星星', sentence: '夜空中有很多星星。', image: 'xing_xing.jpg', translation: 'Star' },
    { character: '太', unicode: '592A', pinyin: 'taiˋ', phrase: '太陽', sentence: '太陽升起了。', image: 'tai_yang.jpg', translation: 'Sun' },
    { character: '陽', unicode: '9633', pinyin: 'yangˊ', phrase: '陽光', sentence: '陽光明媚。', image: 'yang_guang.jpg', translation: 'Sunshine' },
    { character: '來', unicode: '6765', pinyin: 'laiˊ', phrase: '來自', sentence: '他來自中國。', image: 'lai_zi.jpg', translation: 'Come' },
    { character: '月', unicode: '6708', pinyin: 'yueˋ', phrase: '月亮', sentence: '今晚的月亮很圓。', image: 'yue_liang.jpg', translation: 'Moon' },
    { character: '裡', unicode: '88E4', pinyin: 'liˇ', phrase: '裡面', sentence: '我把鑰匙放在了裡面。', image: 'li_mian.jpg', translation: 'Inside' },
    { character: '海', unicode: '6D77', pinyin: 'haiˇ', phrase: '海洋', sentence: '海洋的美麗令人驚嘆。', image: 'hai_yang.jpg', translation: 'Sea' },
    { character: '亮', unicode: '4EAE', pinyin: 'liangˋ', phrase: '明亮', sentence: '房間很明亮。', image: 'ming_liang.jpg', translation: 'Bright' },
    { character: '哪', unicode: '54EA', pinyin: 'naˇ', phrase: '哪裡', sentence: '他去哪裡了？', image: 'na_li.jpg', translation: 'Where' },
    { character: '彩', unicode: '5F69', pinyin: 'caiˇ', phrase: '彩虹', sentence: '彩虹出現了。', image: 'cai_hong.jpg', translation: 'Color' },
    { character: '的', unicode: '7684', pinyin: 'de˙', phrase: '我的', sentence: '這是我的書。', image: 'wo_de.jpg', translation: 'My' },
    { character: '上', unicode: '4E0A', pinyin: 'shangˋ', phrase: '上學', sentence: '他每天都上學。', image: 'shang_xue.jpg', translation: 'Up' },
    { character: '想', unicode: '60F3', pinyin: 'xiangˇ', phrase: '想念', sentence: '我想念我的家人。', image: 'xiang_nian.jpg', translation: 'Miss' },
    { character: '爬', unicode: '722D', pinyin: 'paˊ', phrase: '爬山', sentence: '爬山對身體有益。', image: 'pa_shan.jpg', translation: 'Climb' },
    { character: '沒', unicode: '6CA1', pinyin: 'meiˊ', phrase: '沒有', sentence: '他沒有回來。', image: 'mei_you.jpg', translation: 'Not' },
    { character: '棉', unicode: '68D5', pinyin: 'mianˊ', phrase: '棉花', sentence: '這片土地適合種植棉花。', image: 'mian_hua.jpg', translation: 'Cotton' },
    { character: '下', unicode: '4E0B', pinyin: 'xiaˋ', phrase: '下雨', sentence: '外面下雨了。', image: 'xia_yu.jpg', translation: 'Under' },
    { character: '泡', unicode: '6CE1', pinyin: 'paoˋ', phrase: '泡泡', sentence: '他在玩水泡。', image: 'pao_pao.jpg', translation: 'Bubble' },
    { character: '池', unicode: '6C60', pinyin: 'chiˊ', phrase: '游泳池', sentence: '我們去游泳池游泳。', image: 'you_yong_chi.jpg', translation: 'Pool' },
    { character: '滑', unicode: '6ED1', pinyin: 'huaˊ', phrase: '滑雪', sentence: '我們去山上滑雪。', image: 'hua_xue.jpg', translation: 'Slide' },
    { character: '梯', unicode: '68AF', pinyin: 'ti¯', phrase: '樓梯', sentence: '我住在八樓，每天要爬樓梯。', image: 'lou_ti.jpg', translation: 'Stairs' },
    { character: '糖', unicode: '7CD6', pinyin: 'tangˊ', phrase: '糖果', sentence: '我喜歡吃糖果。', image: 'tang_guo.jpg', translation: 'Candy' },
    { character: '秋', unicode: '79CB', pinyin: 'qiu¯', phrase: '秋天', sentence: '秋天的葉子變黃了。', image: 'qiu_tian.jpg', translation: 'Autumn' },
    { character: '千', unicode: '5343', pinyin: 'qian¯', phrase: '千萬', sentence: '千萬不要忘記了。', image: 'qian_wan.jpg', translation: 'Thousand' },
    { character: '子', unicode: '5B50', pinyin: 'ziˇ', phrase: '小孩子', sentence: '小孩子很喜歡玩。', image: 'xiao_hai_zi.jpg', translation: 'Child' },
    { character: '空', unicode: '7A7A', pinyin: 'kong¯', phrase: '空氣', sentence: '新鮮的空氣令人愉悅。', image: 'kong_qi.jpg', translation: 'Air' },
    { character: '說', unicode: '8BF4', pinyin: 'shuo¯', phrase: '說話', sentence: '他很會說話。', image: 'shuo_hua.jpg', translation: 'Speak' },
    { character: '早', unicode: '65E9', pinyin: 'zaoˇ', phrase: '早上', sentence: '我每天早上七點起床。', image: 'zao_shang.jpg', translation: 'Early' },
    { character: '向', unicode: '5411', pinyin: 'xiangˋ', phrase: '向前', sentence: '向前走。', image: 'xiang_qian.jpg', translation: 'Forward' },
    { character: '是', unicode: '662F', pinyin: 'shiˋ', phrase: '是不是', sentence: '你是不是聽到了聲音？', image: 'shi_bu_shi.jpg', translation: 'Is' },
    { character: '誰', unicode: '8C01', pinyin: 'sheiˊ', phrase: '誰來了', sentence: '誰來了？', image: 'shui_lai_le.jpg', translation: 'Who' },
    { character: '陪', unicode: '966A', pinyin: 'peiˊ', phrase: '陪伴', sentence: '我們一起陪伴他。', image: 'pei_ban.jpg', translation: 'Accompany' },
    { character: '他', unicode: '4ED6', pinyin: 'ta¯', phrase: '他們', sentence: '他們是我的朋友。', image: 'ta_men.jpg', translation: 'He' },
    { character: '低', unicode: '4F4E', pinyin: 'di¯', phrase: '低音', sentence: '這個音樂有一個很低的低音。', image: 'di_yin.jpg', translation: 'Low' },
    { character: '找', unicode: '627E', pinyin: 'zhaoˇ', phrase: '找工作', sentence: '他正在找工作。', image: 'zhao_gong_zuo.jpg', translation: 'Find' },
    { character: '回', unicode: '56DE', pinyin: 'huiˊ', phrase: '回家', sentence: '我已經回家了。', image: 'hui_jia.jpg', translation: 'Back' },
    { character: '山', unicode: '5C71', pinyin: 'shan¯', phrase: '大山', sentence: '他們攀登了一座大山。', image: 'da_shan.jpg', translation: 'Mountain' },
    { character: '到', unicode: '5230', pinyin: 'daoˋ', phrase: '到達', sentence: '我們終於到達目的地了。', image: 'dao_da.jpg', translation: 'Arrive' },
    { character: '我', unicode: '6211', pinyin: 'woˇ', phrase: '我們', sentence: '我們是好朋友。', image: 'wo_men.jpg', translation: 'I' },
    { character: '叫', unicode: '53EB', pinyin: 'jiaoˋ', phrase: '叫聲', sentence: '他聽到了一聲叫聲。', image: 'jiao_sheng.jpg', translation: 'Call' },
    { character: '人', unicode: '4EBA', pinyin: 'renˊ', phrase: '人類', sentence: '人類是社會的一部分。', image: 'ren_lei.jpg', translation: 'People' },
    { character: '開', unicode: '5F00', pinyin: 'kai¯', phrase: '開心', sentence: '她很開心。', image: 'kai_xin.jpg', translation: 'Happy' },
    { character: '心', unicode: '5FC3', pinyin: 'xin¯', phrase: '心情', sentence: '我現在的心情很好。', image: 'xin_qing.jpg', translation: 'Heart' },
    { character: '嗎', unicode: '541E', pinyin: 'ma˙', phrase: '好不好', sentence: '你好嗎？', image: 'hao_bu_hao.jpg', translation: 'Question' },
    { character: '也', unicode: '4E5F', pinyin: 'yeˇ', phrase: '也許', sentence: '也許是我記錯了。', image: 'ye_xu.jpg', translation: 'Also' },
    { character: '笑', unicode: '7B11', pinyin: 'xiaoˋ', phrase: '笑臉', sentence: '他對著我笑了。', image: 'xiao_lian.jpg', translation: 'Laugh' },
    { character: '哈', unicode: '54C8', pinyin: 'ha¯', phrase: '哈哈', sentence: '他大聲笑了。', image: 'ha_ha.jpg', translation: 'Haha' },
    { character: '音', unicode: '97F3', pinyin: 'yin¯', phrase: '音樂', sentence: '我喜歡聽音樂。', image: 'yin_yue.jpg', translation: 'Music' },
    { character: '谷', unicode: '8C37', pinyin: 'guˇ', phrase: '山谷', sentence: '美國最有名的山谷叫大峽谷。', image: 'gu_wu.jpg', translation: 'Valley' },
    { character: '們', unicode: '4EEC', pinyin: 'men˙', phrase: '我們', sentence: '我們是好朋友。', image: 'wo_men.jpg', translation: 'We' },
    { character: '狗', unicode: '72AC', pinyin: 'gouˇ', phrase: '小狗', sentence: '小狗在跳。', translation: 'Dog' },
    { character: '冬', unicode: '51AC', pinyin: 'dong¯', phrase: '冬天', sentence: '冬天很冷。', translation: 'Winter' },
    { character: '當', unicode: '7576', pinyin: 'dang¯', phrase: '當時', sentence: '當時我不在家。', translation: 'When' },
    { character: '朋', unicode: '670B', pinyin: 'pengˊ', phrase: '朋友', sentence: '他是我的朋友。', translation: 'Friend' },
    { character: '友', unicode: '53CB', pinyin: 'youˇ', phrase: '朋友', sentence: '我們是朋友。', translation: 'Friend' },
    { character: '冷', unicode: '51B7', pinyin: 'lengˇ', phrase: '冷水', sentence: '他喝了一杯冷水。', translation: 'Cold' },
    { character: '冰', unicode: '51B0', pinyin: 'bing¯', phrase: '冰塊', sentence: '冰塊在融化。', translation: 'Ice' },
    { character: '不', unicode: '4E0D', pinyin: 'buˋ', phrase: '不好', sentence: '這個主意不好。', translation: 'Not' },
    { character: '話', unicode: '8A71', pinyin: 'huaˋ', phrase: '說話', sentence: '請大聲點說話。', translation: 'Talk' },
    { character: '急', unicode: '6025', pinyin: 'jiˊ', phrase: '急忙', sentence: '他急忙離開了。', translation: 'Urgent' },
    { character: '忙', unicode: '5FD9', pinyin: 'mangˊ', phrase: '忙碌', sentence: '他一直很忙碌。', translation: 'Busy' },
    { character: '色', unicode: '8272', pinyin: 'seˋ', phrase: '顏色', sentence: '這種顏色很漂亮。', translation: 'Color' },
    { character: '洗', unicode: '6D17', pinyin: 'xiˇ', phrase: '洗澡', sentence: '他在洗澡。', translation: 'Wash' },
    { character: '澡', unicode: '6FA1', pinyin: 'zaoˇ', phrase: '洗澡', sentence: '洗澡可以放鬆。', translation: 'Bath' },
    { character: '還', unicode: '9084', pinyin: 'haiˊ', phrase: '還好', sentence: '他還好嗎？', translation: 'Still' },
    { character: '風', unicode: '98A8', pinyin: 'feng¯', phrase: '風景', sentence: '風很大。', translation: 'Wind' },
    { character: '兒', unicode: '5152', pinyin: 'erˊ', phrase: '兒子', sentence: '他的兒子很聰明。', translation: 'Son' },
    { character: '愛', unicode: '611B', pinyin: 'aiˋ', phrase: '愛情', sentence: '愛是美好的。', translation: 'Love' },
    { character: '找', unicode: '627E', pinyin: 'zhaoˇ', phrase: '找錢', sentence: '他在找工作。', translation: 'Find' },
    { character: '春', unicode: '6625', pinyin: 'chun¯', phrase: '春天', sentence: '春天來了。', translation: 'Spring' },
    { character: '綠', unicode: '7DA0', pinyin: 'luˋ', phrase: '綠色', sentence: '草地很綠。', translation: 'Green' },
    { character: '牛', unicode: '725B', pinyin: 'niuˊ', phrase: '牛奶', sentence: '牛在吃草。', translation: 'Cow' },
    { character: '跟', unicode: '8DDF', pinyin: 'gen¯', phrase: '跟著', sentence: '跟我來。', translation: 'With' },
    { character: '直', unicode: '76F4', pinyin: 'zhiˊ', phrase: '直接', sentence: '直飛是快的。', translation: 'Direct' },
    { character: '們', unicode: '5011', pinyin: 'men˙', phrase: '我們', sentence: '我們一起去。', translation: 'We' },
    { character: '吧', unicode: '5427', pinyin: 'ba˙', phrase: '走吧', sentence: '我們走吧。', translation: 'Bar' },
    { character: '拉', unicode: '62C9', pinyin: 'la¯', phrase: '拉手', sentence: '拉著我的手。', translation: 'Pull' },
    { character: '著', unicode: '8457', pinyin: 'zhe˙', phrase: '看著', sentence: '火車駛著。', translation: 'Wearing' },
    { character: '伸', unicode: '4F38', pinyin: 'shen¯', phrase: '伸手', sentence: '伸出你的手。', translation: 'Extend' },
    { character: '手', unicode: '624B', pinyin: 'shouˇ', phrase: '手錶', sentence: '他舉起手。', translation: 'Hand' },
    { character: '抱', unicode: '62B1', pinyin: 'baoˋ', phrase: '抱歉', sentence: '抱起孩子。', translation: 'Hold' },
    { character: '得', unicode: '5F97', pinyin: 'deˊ', phrase: '得到', sentence: '我得到了它。', translation: 'Obtain' },
    { character: '溫', unicode: '6EAB', pinyin: 'wen¯', phrase: '溫度', sentence: '溫度很高。', translation: 'Warm' },
    { character: '覺', unicode: '89BA', pinyin: 'jueˊ', phrase: '感覺', sentence: '我覺得很好。', translation: 'Feel' },
    { character: '暖', unicode: '6696', pinyin: 'nuanˇ', phrase: '暖氣', sentence: '房間很暖和。', translation: 'Warm' },
    { character: '地', unicode: '5730', pinyin: 'diˋ', phrase: '地圖', sentence: '地板很乾淨。', translation: 'Ground' },
    { character: '跑', unicode: '8DD1', pinyin: 'paoˇ', phrase: '跑步', sentence: '他喜歡在公園裡跑步。', translation: 'Run' },
    { character: '聞', unicode: '805E', pinyin: 'wenˊ', phrase: '聞名', sentence: '這家餐廳很聞名。', translation: 'Smell' },
    { character: '香', unicode: '9999', pinyin: 'xiang¯', phrase: '香水', sentence: '她喜歡這款香水。', translation: 'Fragrant' },
    { character: '朵', unicode: '6735', pinyin: 'duoˇ', phrase: '花朵', sentence: '花園裡有很多花朵。', translation: 'Flower' },
    { character: '真', unicode: '771F', pinyin: 'zhen¯', phrase: '真相', sentence: '我們需要找到真相。', translation: 'Real' },
    { character: '漂', unicode: '6F02', pinyin: 'piao¯', phrase: '漂亮', sentence: '這幅畫很漂亮。', translation: 'Float' },
    { character: '亮', unicode: '4EAE', pinyin: 'liangˋ', phrase: '明亮', sentence: '房間非常亮。', translation: 'Bright' },
    { character: '原', unicode: '539F', pinyin: 'yuanˊ', phrase: '原因', sentence: '他解釋了原因。', translation: 'Original' },
    { character: '等', unicode: '7B49', pinyin: 'dengˇ', phrase: '等待', sentence: '我們在這裡等你。', translation: 'Wait' },
    { character: '介', unicode: '4EC7', pinyin: 'jieˋ', phrase: '介紹', sentence: '讓我來介紹一下自己。', translation: 'Introduce' },
    { character: '紹', unicode: '7D39', pinyin: 'shaoˋ', phrase: '介紹', sentence: '他將會介紹這個計劃。', translation: 'Introduce' },
    { character: '自', unicode: '81EA', pinyin: 'ziˋ', phrase: '自己', sentence: '他喜歡獨自旅行。', translation: 'Self' },
    { character: '己', unicode: '5DF1', pinyin: 'jiˇ', phrase: '自己', sentence: '每個人都應該照顧自己。', translation: 'Self' },
    { character: '做', unicode: '505A', pinyin: 'zuoˋ', phrase: '做飯', sentence: '今晚我來做飯。', translation: 'Do' },
    { character: '樣', unicode: '6A23', pinyin: 'yangˋ', phrase: '樣子', sentence: '這個樣子很奇怪。', translation: 'Style' },
    { character: '顏', unicode: '984F', pinyin: 'yanˊ', phrase: '顏色', sentence: '我喜歡這種顏色。', translation: 'Color' },
    { character: '送', unicode: '9001', pinyin: 'songˋ', phrase: '送禮', sentence: '他決定送一份禮物。', translation: 'Send' },
    { character: '什', unicode: '4EC0', pinyin: 'shenˊ', phrase: '什麼', sentence: '你想要什麼？', translation: 'What' },
    { character: '麼', unicode: '9EBC', pinyin: 'me˙', phrase: '什麼', sentence: '這是什麼意思？', translation: 'What' },
    { character: '呢', unicode: '5462', pinyin: 'ne˙', phrase: '呢', sentence: '你怎麼了呢？', translation: 'Particle' },
    { character: '媽', unicode: '5ABD', pinyin: 'ma¯', phrase: '媽媽', sentence: '媽媽在廚房。', translation: 'Mother' },
    { character: '生', unicode: '751F', pinyin: 'sheng¯', phrase: '生日', sentence: '明天是他的生日。', translation: 'Birth' },
    { character: '日', unicode: '65E5', pinyin: 'riˋ', phrase: '生日', sentence: '生日快樂！', translation: 'Day' },
    { character: '快', unicode: '5FEB', pinyin: 'kuaiˋ', phrase: '快樂', sentence: '大家都很快樂。', translation: 'Fast' },
    { character: '爸', unicode: '7238', pinyin: 'baˋ', phrase: '爸爸', sentence: '爸爸在工作。', translation: 'Dad' },
    { character: '姐', unicode: '59D0', pinyin: 'jieˇ', phrase: '姐姐', sentence: '姐姐正在學習。', translation: 'Older sister' },
    { character: '會', unicode: '6703', pinyin: 'huiˋ', phrase: '會議', sentence: '會議在哪裡舉行？', translation: 'Can' },
    { character: '張', unicode: '5F35', pinyin: 'zhang¯', phrase: '張紙', sentence: '這張紙是空的。', translation: 'Sheet' },
    { character: '卡', unicode: '5361', pinyin: 'kaˇ', phrase: '卡片', sentence: '他給我一張卡片。', translation: 'Card' },
    { character: '片', unicode: '7247', pinyin: 'pianˋ', phrase: '卡片', sentence: '雲朵像片片棉花。', translation: 'Slice' },
    { character: '給', unicode: '7D66', pinyin: 'geiˇ', phrase: '給我', sentence: '請給我那本書。', translation: 'Give' },
    { character: '寫', unicode: '5BEB', pinyin: 'xieˇ', phrase: '寫字', sentence: '我喜歡寫日記。', translation: 'Write' },
    { character: '畫', unicode: '756B', pinyin: 'huaˋ', phrase: '畫畫', sentence: '她正在畫畫。', translation: 'Paint' },
    { character: '外', unicode: '5916', pinyin: 'waiˋ', phrase: '外面', sentence: '外面正在下雨。', translation: 'Outside' },
    { character: '麻', unicode: '9EBB', pinyin: 'maˊ', phrase: '麻雀', sentence: '麻雀在樹上唱歌。', translation: 'Numb' },
    { character: '雀', unicode: '96C0', pinyin: 'queˋ', phrase: '麻雀', sentence: '麻雀很小巧。', translation: 'Sparrow' },
    { character: '字', unicode: '5B57', pinyin: 'ziˋ', phrase: '寫字', sentence: '學寫字很有趣。', translation: 'Character' },
    { character: '但', unicode: '4F46', pinyin: 'danˋ', phrase: '但是', sentence: '我想去，但是太遠了。', translation: 'But' },
    { character: '課', unicode: '8AB2', pinyin: 'keˋ', phrase: '課程', sentence: '今天的課很有意思。', translation: 'Class' },
    { character: '才', unicode: '624D', pinyin: 'caiˊ', phrase: '才能', sentence: '他才來不久。', translation: 'Only' },
    { character: '可', unicode: '53EF', pinyin: 'keˇ', phrase: '可以', sentence: '這件事可以做。', translation: 'Can' },
    { character: '以', unicode: '4EE5', pinyin: 'yiˇ', phrase: '可以', sentence: '可以用這個方法。', translation: 'With' },
    { character: '又', unicode: '53C8', pinyin: 'youˋ', phrase: '又來', sentence: '他又來晚了。', translation: 'Again' },
    { character: '跳', unicode: '8DF3', pinyin: 'tiaoˋ', phrase: '跳舞', sentence: '孩子們在跳舞。', translation: 'Jump' },
    { character: '停', unicode: '505C', pinyin: 'tingˊ', phrase: '停車', sentence: '車子停在那裡。', translation: 'Stop' },
    { character: '先', unicode: '5148', pinyin: 'xian¯', phrase: '先生', sentence: '你先走。', translation: 'First' },
    { character: '再', unicode: '518D', pinyin: 'zaiˋ', phrase: '再見', sentence: '我們再見面吧。', translation: 'Again' },
    { character: '窗', unicode: '7A97', pinyin: 'chuang¯', phrase: '窗戶', sentence: '窗外的風景很美。', translation: 'Window' },
    { character: '遊', unicode: '904A', pinyin: 'youˊ', phrase: '遊戲', sentence: '孩子們喜歡玩遊戲。', translation: 'Play' },
    { character: '戲', unicode: '6232', pinyin: 'xiˋ', phrase: '遊戲', sentence: '這是一款好玩的遊戲。', translation: 'Game' },
    { character: '毛', unicode: '6BDB', pinyin: 'maoˊ', phrase: '毛巾', sentence: '他用毛巾擦臉。', translation: 'Fur' },
    { character: '蟲', unicode: '87F2', pinyin: 'chongˊ', phrase: '毛蟲', sentence: '毛蟲爬上了樹。', translation: 'Insect' },
    { character: '過', unicode: '904E', pinyin: 'guoˋ', phrase: '過河', sentence: '我們必須過河。', translation: 'Cross' },
    { character: '河', unicode: '6CB3', pinyin: 'heˊ', phrase: '河流', sentence: '這條河流很寬。', translation: 'River' },
    { character: '站', unicode: '7AD9', pinyin: 'zhanˋ', phrase: '站立', sentence: '請站起來。', translation: 'Stand' },
    { character: '魚', unicode: '9B5A', pinyin: 'yuˊ', phrase: '魚類', sentence: '海裡有很多魚。', translation: 'Fish' },
    { character: '游', unicode: '6CF3', pinyin: 'youˊ', phrase: '游泳', sentence: '孩子們喜歡游泳。', translation: 'Swim' },
    { character: '哇', unicode: '54C7', pinyin: 'waˊ', phrase: '哇', sentence: '哇！這麼多魚！', translation: 'Wow' },
    { character: '青', unicode: '9752', pinyin: 'qing¯', phrase: '青蛙', sentence: '池塘裡有很多青蛙。', translation: 'Green' },
    { character: '蛙', unicode: '86D9', pinyin: 'wa¯', phrase: '青蛙', sentence: '青蛙在池塘裡唱歌。', translation: 'Frog' },
    { character: '幫', unicode: '5E6B', pinyin: 'bang¯', phrase: '幫忙', sentence: '她幫忙做家務。', translation: 'Help' },
    { character: '面', unicode: '9762', pinyin: 'mianˋ', phrase: '正面', sentence: '他站在我面前。', translation: 'Face' },
    { character: '葉', unicode: '8449', pinyin: 'yeˋ', phrase: '樹葉', sentence: '樹葉變黃了。', translation: 'Leaf' },
    { character: '坐', unicode: '5750', pinyin: 'zuoˋ', phrase: '坐下', sentence: '請坐在椅子上。', translation: 'Sit' },
    { character: '船', unicode: '8239', pinyin: 'chuanˊ', phrase: '船隻', sentence: '他們坐在船上。', translation: 'Boat' },
    { character: '推', unicode: '63A8', pinyin: 'tui¯', phrase: '推開', sentence: '請推開門。', translation: 'Push' },
    { character: '邊', unicode: '908A', pinyin: 'bian¯', phrase: '旁邊', sentence: '他站在旁邊。', translation: 'Side' },
    { character: '借', unicode: '501F', pinyin: 'jieˋ', phrase: '借書', sentence: '我去圖書館借書。', translation: 'Borrow' },
    { character: '筆', unicode: '7B46', pinyin: 'biˇ', phrase: '鉛筆', sentence: '請借我一支筆。', translation: 'Pen' },
    { character: '她', unicode: '5979', pinyin: 'ta¯', phrase: '她們', sentence: '她在學校。', translation: 'She' },
    { character: '就', unicode: '5C31', pinyin: 'jiuˋ', phrase: '就要', sentence: '他就要出發了。', translation: 'Then' },
    { character: '把', unicode: '628A', pinyin: 'baˇ', phrase: '把手', sentence: '請握緊把手。', translation: 'Handle' },
    { character: '拿', unicode: '62FF', pinyin: 'naˊ', phrase: '拿起', sentence: '他拿起書本。', translation: 'Take' },
    { character: '很', unicode: '5F88', pinyin: 'henˇ', phrase: '很好', sentence: '這道菜很好吃。', translation: 'Very' },
    { character: '都', unicode: '90FD', pinyin: 'dou¯', phrase: '都到', sentence: '他們都到了。', translation: 'All' },
    { character: '前', unicode: '524D', pinyin: 'qianˊ', phrase: '前面', sentence: '他站在前面。', translation: 'Front' },
    { character: '每', unicode: '6BCF', pinyin: 'meiˇ', phrase: '每天', sentence: '每天早上他去跑步。', translation: 'Every' },
    { character: '家', unicode: '5BB6', pinyin: 'jia¯', phrase: '家人', sentence: '家裡很溫暖。', translation: 'Home' },
    { character: '今', unicode: '4ECA', pinyin: 'jin¯', phrase: '今天', sentence: '今天是星期五。', translation: 'Today' },
    { character: '背', unicode: '80CC', pinyin: 'beiˋ', phrase: '後背', sentence: '我的背需要按摩。', translation: 'Back' },
    { character: '書', unicode: '66F8', pinyin: 'shu¯', phrase: '書本', sentence: '書架上滿是書。', translation: 'Book' },
    { character: '包', unicode: '5305', pinyin: 'bao¯', phrase: '背包', sentence: '他的包裡有很多東西。', translation: 'Bag' },
    { character: '剛', unicode: '525B', pinyin: 'gang¯', phrase: '剛好', sentence: '他剛走不久。', translation: 'Just' },
    { character: '興', unicode: '8208', pinyin: 'xingˋ', phrase: '興趣', sentence: '他對音樂很有興趣。', translation: 'Interest' },
    { character: '整', unicode: '6574', pinyin: 'zhengˇ', phrase: '整理', sentence: '整理房間很重要。', translation: 'Entire' },
    { character: '數', unicode: '6578', pinyin: 'shuˋ', phrase: '數字', sentence: '數學是學習數字的科學。', translation: 'Number' },
    { character: '完', unicode: '5B8C', pinyin: 'wanˊ', phrase: '完成', sentence: '工作已經完成。', translation: 'Complete' },
    { character: '氣', unicode: '6C23', pinyin: 'qiˋ', phrase: '氣氛', sentence: '氣氛很緊張。', translation: 'Air' },
    { character: '知', unicode: '77E5', pinyin: 'zhi¯', phrase: '知道', sentence: '我不知道答案。', translation: 'Know' },
    { character: '道', unicode: '9053', pinyin: 'daoˋ', phrase: '道路', sentence: '這條道很窄。', translation: 'Way' },
    { character: '該', unicode: '8A72', pinyin: 'gai¯', phrase: '該死', sentence: '該怎麼做呢？', translation: 'Should' },
    { character: '東', unicode: '6771', pinyin: 'dong¯', phrase: '東西', sentence: '東邊的天空很亮。', translation: 'East' },
    { character: '西', unicode: '897F', pinyin: 'xi¯', phrase: '東西', sentence: '西方文化很有趣。', translation: 'West' },
    { character: '句', unicode: '53E5', pinyin: 'juˋ', phrase: '句子', sentence: '這句話很有意思。', translation: 'Sentence' },
    { character: '冒', unicode: '5192', pinyin: 'maoˋ', phrase: '冒險', sentence: '冒險是他的愛好。', translation: 'Venture' },
    { character: '像', unicode: '50CF', pinyin: 'xiangˋ', phrase: '像素', sentence: '這張照片像真的一樣。', translation: 'Image' },
    { character: '樣', unicode: '6A23', pinyin: 'yangˋ', phrase: '樣子', sentence: '他的做事樣子很專業。', translation: 'Style' },
    { character: '越', unicode: '8D8A', pinyin: 'yueˋ', phrase: '越來越', sentence: '天氣越來越冷。', translation: 'More and more' },
    { character: '能', unicode: '80FD', pinyin: 'nengˊ', phrase: '能力', sentence: '他有很強的領導能力。', translation: 'Can' },
    { character: '對', unicode: '5C0D', pinyin: 'duiˋ', phrase: '對話', sentence: '我們需要有一次認真的對話。', translation: 'Correct' },
    { character: '兩', unicode: '5169', pinyin: 'liangˇ', phrase: '兩個', sentence: '我買了兩個蘋果。', translation: 'Two' },
    { character: '教', unicode: '6559', pinyin: 'jiao¯', phrase: '教室', sentence: '教室裡很安靜。', translation: 'Teach' },
    { character: '室', unicode: '5BA4', pinyin: 'shiˋ', phrase: '教室', sentence: '這間室內裝修很新。', translation: 'Room' },
    { character: '桌', unicode: '684C', pinyin: 'zhuo¯', phrase: '桌子', sentence: '桌子上放著很多書。', translation: 'Table' },
    { character: '意', unicode: '610F', pinyin: 'yiˋ', phrase: '意思', sentence: '他的話有特別的意思。', translation: 'Meaning' },
    { character: '思', unicode: '601D', pinyin: 'si¯', phrase: '意思', sentence: '他在思考一個難題。', translation: 'Thought' },
    { character: '個', unicode: '500B', pinyin: 'geˊ', phrase: 'ㄧ個', sentence: '每個人都有自己的選擇。', translation: 'Unit' },
    { character: '中', unicode: '4E2D', pinyin: 'zhong¯', phrase: '中間', sentence: '我們坐在教室中間。', translation: 'Middle' },
    { character: '忍', unicode: '5FCD', pinyin: 'renˇ', phrase: '忍耐', sentence: '他忍不住笑了起來。', translation: 'Endure' },
    { character: '住', unicode: '4F4F', pinyin: 'zhuˋ', phrase: '住宿', sentence: '我們在那家酒店住了一晚。', translation: 'Reside' },
    { character: '忽', unicode: '5FDD', pinyin: 'hu¯', phrase: '忽然', sentence: '忽然之間，天空變暗了。', translation: 'Suddenly' },
    { character: '然', unicode: '7136', pinyin: 'ranˊ', phrase: '忽然', sentence: '然後他就走了。', translation: 'However' },
    { character: '啊', unicode: '554A', pinyin: 'a˙', phrase: '啊', sentence: '啊，真的嗎？', translation: 'Ah' },
    { character: '畫', unicode: '756B', pinyin: 'huaˋ', phrase: '畫畫', sentence: '他喜歡畫畫。', translation: 'Paint' },
    { character: '忘', unicode: '5FD8', pinyin: 'wangˋ', phrase: '忘記', sentence: '我忘記帶鑰匙了。', translation: 'Forget' },
    { character: '用', unicode: '7528', pinyin: 'yongˋ', phrase: '使用', sentence: '請小心使用這台機器。', translation: 'Use' },
    { character: '帶', unicode: '5E26', pinyin: 'daiˋ', phrase: '帶來', sentence: '他帶來了一些好消息。', translation: 'Bring' },
    { character: '芽', unicode: '82BD', pinyin: 'yaˊ', phrase: '芽', sentence: '新芽從土裡長出來了。', translation: 'Bud' },
    { character: '打', unicode: '6253', pinyin: 'daˇ', phrase: '打電話', sentence: '他正在打電話。', translation: 'Hit' },
    { character: '雷', unicode: '96F7', pinyin: 'leiˊ', phrase: '打雷', sentence: '聽，外面在打雷。', translation: 'Thunder' },
    { character: '土', unicode: '571F', pinyin: 'tuˇ', phrase: '土地', sentence: '土地非常肥沃。', translation: 'Soil' },
    { character: '抖', unicode: '6296', pinyin: 'douˇ', phrase: '抖動', sentence: '樹葉在風中抖動。', translation: 'Shake' },
    { character: '害', unicode: '5BB3', pinyin: 'haiˋ', phrase: '害怕', sentence: '他害怕黑暗。', translation: 'Harm' },
    { character: '怕', unicode: '6015', pinyin: 'paˋ', phrase: '害怕', sentence: '不要怕，我在這裡。', translation: 'Afraid' },
    { character: '咬', unicode: '54AC', pinyin: 'yaoˇ', phrase: '咬人', sentence: '狗咬了一個人。', translation: 'Bite' },
    { character: '樹', unicode: '6A39', pinyin: 'shuˋ', phrase: '樹木', sentence: '這棵樹很大。', translation: 'Tree' },
    { character: '暖', unicode: '6696', pinyin: 'nuanˇ', phrase: '暖和', sentence: '太陽讓空氣變得暖和。', translation: 'Warm' },
    { character: '風', unicode: '98A8', pinyin: 'feng¯', phrase: '風力', sentence: '風很大，難以行走。', translation: 'Wind' },
    { character: '兒', unicode: '5152', pinyin: 'erˊ', phrase: '兒童', sentence: '公園裡有很多玩耍的兒童。', translation: 'Child' },
    { character: '勇', unicode: '52C7', pinyin: 'yongˇ', phrase: '勇敢', sentence: '他是一個勇敢的人。', translation: 'Brave' },
    { character: '敢', unicode: '6562', pinyin: 'ganˇ', phrase: '勇敢', sentence: '你敢不敢嘗試一下？', translation: 'Dare' },
    { character: '這', unicode: '9019', pinyin: 'zhe', phrase: '這些', sentence: '這是什麼？', translation: 'This' },
    { character: '棵', unicode: '68F5', pinyin: 'ke¯', phrase: '一棵樹', sentence: '院子裡種了一棵樹。', translation: 'Measure word for trees' },
    { character: '發', unicode: '767C', pinyin: 'fa¯', phrase: '發展', sentence: '公司的業務正在快速發展。', translation: 'Send out' },
    { character: '柔', unicode: '67D4', pinyin: 'rouˊ', phrase: '柔軟', sentence: '這塊布料很柔軟。', translation: 'Soft' },
    { character: '雙', unicode: '96D9', pinyin: 'shuang¯', phrase: '雙手', sentence: '他用雙手舉起了那個箱子。', translation: 'Pair' },
    { character: '聽', unicode: '807D', pinyin: 'ting¯', phrase: '聽見', sentence: '你聽見那個聲音了嗎？', translation: 'Listen' },
    { character: '鉛', unicode: '9285', pinyin: 'qian¯', phrase: '鉛筆', sentence: '他用鉛筆寫字。', translation: 'Lead' },
    { character: '橡', unicode: '6A61', pinyin: 'xiangˋ', phrase: '橡膠', sentence: '這是橡膠製的。', translation: 'Rubber' },
    { character: '皮', unicode: '76AE', pinyin: 'piˊ', phrase: '皮膚', sentence: '她的皮膚非常光滑。', translation: 'Skin' },
    { character: '常', unicode: '5E38', pinyin: 'changˊ', phrase: '常常', sentence: '他常常來這裡。', translation: 'Often' },
    { character: '錯', unicode: '932F', pinyin: 'cuoˋ', phrase: '錯誤', sentence: '這是一個常見的錯誤。', translation: 'Mistake' },
    { character: '久', unicode: '4E45', pinyin: 'jiuˇ', phrase: '長久', sentence: '我們已經認識很久了。', translation: 'Long time' },
    { character: '哭', unicode: '54ED', pinyin: 'ku¯', phrase: '哭泣', sentence: '孩子跌倒了，開始哭泣。', translation: 'Cry' },
    { character: '加', unicode: '52A0', pinyin: 'jia¯', phrase: '加油', sentence: '比賽時大家都在喊加油。', translation: 'Add' },
    { character: '油', unicode: '6CB9', pinyin: 'youˊ', phrase: '加油', sentence: '車子需要加油了。', translation: 'Oil' },
    { character: '試', unicode: '8A66', pinyin: 'shiˋ', phrase: '試驗', sentence: '他正在進行一個科學試驗。', translation: 'Try' },
    { character: '後', unicode: '5F8C', pinyin: 'houˋ', phrase: '之後', sentence: '放學後我們去公園。', translation: 'After' },
    { character: '正', unicode: '6B63', pinyin: 'zhengˋ', phrase: '正確', sentence: '他的回答是正確的。', translation: 'Correct' },
    { character: '進', unicode: '9032', pinyin: 'jinˋ', phrase: '進步', sentence: '他的學習進步很大。', translation: 'Enter' },
    { character: '步', unicode: '6B65', pinyin: 'buˋ', phrase: '進步', sentence: '一步一個腳印。', translation: 'Step' },
    { character: '需', unicode: '9700', pinyin: 'xu¯', phrase: '需要', sentence: '完成這項工作需要時間。', translation: 'Need' },
    { character: '學', unicode: '5B78', pinyin: 'xueˊ', phrase: '學習', sentence: '他在學習新技能。', translation: 'Learn' },
    { character: '擦', unicode: '64AB', pinyin: 'ca¯', phrase: '擦窗戶', sentence: '他正在擦桌子。', translation: 'Wipe' },
    { character: '確', unicode: '78BA', pinyin: 'queˋ', phrase: '確定', sentence: '我們需要確定會議的日期。', translation: 'Sure' },
    { character: '期', unicode: '671F', pinyin: 'qi¯', phrase: '期待', sentence: '我期待與你的見面。', translation: 'Period' },
    { character: '全', unicode: '5168', pinyin: 'quanˊ', phrase: '全部', sentence: '全班同學都來了。', translation: 'All' },
    { character: '班', unicode: '73ED', pinyin: 'ban¯', phrase: '班級', sentence: '他是我們班的班長。', translation: 'Class' },
    { character: '故', unicode: '6545', pinyin: 'guˋ', phrase: '故事', sentence: '她喜歡聽奶奶講故事。', translation: 'Old' },
    { character: '事', unicode: '4E8B', pinyin: 'shiˋ', phrase: '故事', sentence: '事實勝於雄辯。', translation: 'Matter' },
    { character: '記', unicode: '8A18', pinyin: 'jiˋ', phrase: '記錄', sentence: '請記下這些重要的日期。', translation: 'Record' },
    { character: '決', unicode: '6C7A', pinyin: 'jueˊ', phrase: '決定', sentence: '我們已經做出了決定。', translation: 'Decide' },
    { character: '定', unicode: '5B9A', pinyin: 'dingˋ', phrase: '決定', sentence: '位置已經定好了。', translation: 'Set' },
    { character: '狼', unicode: '72FC', pinyin: 'langˊ', phrase: '狼來了', sentence: '狼是一種野生動物。', translation: 'Wolf' },
    { character: '時', unicode: '6642', pinyin: 'shiˊ', phrase: '時間', sentence: '現在是什麼時間？', translation: 'Time' },
    { character: '間', unicode: '9593', pinyin: 'jian¯', phrase: '時間', sentence: '他在房間裡休息。', translation: 'Between' },
    { character: '段', unicode: '6BB5', pinyin: 'duanˋ', phrase: '一段時間', sentence: '他講了一段有趣的故事。', translation: 'Section' },
    { character: '動', unicode: '52D5', pinyin: 'dongˋ', phrase: '活動', sentence: '這個機器可以自動運行。', translation: 'Move' },
    { character: '物', unicode: '7269', pinyin: 'wuˋ', phrase: '物品', sentence: '他的房間裡滿是各種物品。', translation: 'Object' },
    { character: '同', unicode: '540C', pinyin: 'tongˊ', phrase: '同學', sentence: '他們是我的同學。', translation: 'Same' },
    { character: '拍', unicode: '62CD', pinyin: 'pai¯', phrase: '拍照', sentence: '她在拍照片。', translation: 'Clap' },
    { character: '臺', unicode: '81FA', pinyin: 'taiˊ', phrase: '臺灣', sentence: '臺灣是一個美麗的地方。', translation: 'Platform' },
    { character: '演', unicode: '6F14', pinyin: 'yanˇ', phrase: '演出', sentence: '他將在今晚的演出中表演。', translation: 'Perform' }
];

export const secondGrade = [
];

export const thirdGrade = [
];

export const fourthGrade = [

];

export const fifthGrade = [

];

export const sixthGrade = [

];
