export const firstGrade = [
    { character: '小', unicode: '5C0F', pinyin: 'xiaoˇ', phrase: '小狗', sentence: '小狗很可愛。', image: 'xiao_gou.jpg', translation: 'Small' },
    { character: '羊', unicode: '7F8A', pinyin: 'yangˊ', phrase: '小羊', sentence: '小羊在吃草。', image: 'xiao_yang.jpg', translation: 'Sheep' },
    { character: '草', unicode: '8349', pinyin: 'caoˇ', phrase: '草地', sentence: '他在草地上玩。', image: 'cao_di.jpg', translation: 'Grass' },
    { character: '吃', unicode: '5403', pinyin: 'chi¯', phrase: '吃飯', sentence: '他在吃飯。', image: 'chi_fan.jpg', translation: 'Eat' },
    { character: '天', unicode: '5929', pinyin: 'tian¯', phrase: '天空', sentence: '天空很藍。', image: 'tian_kong.jpg', translation: 'Sky' },
    { character: '少', unicode: '5C11', pinyin: 'shaoˋ', phrase: '少年', sentence: '他是一個少年。', image: 'shao_nian.jpg', translation: 'Young' },
    { character: '高', unicode: '9AD8', pinyin: 'gao¯', phrase: '高山', sentence: '我們登上了高山。', image: 'gao_shan.jpg', translation: 'High' },
    { character: '出', unicode: '51FA', pinyin: 'chu¯', phrase: '出去', sentence: '他出去了。', image: 'chu_qu.jpg', translation: 'Go out' },
    { character: '門', unicode: '95E8', pinyin: 'menˊ', phrase: '門口', sentence: '我站在門口。', image: 'men_kou.jpg', translation: 'Door' },
    { character: '去', unicode: '53BB', pinyin: 'quˋ', phrase: '去年', sentence: '去年我去了中國。', image: 'qu_nian.jpg', translation: 'Go' },
    { character: '開', unicode: '5F00', pinyin: 'kai¯', phrase: '開心', sentence: '他很開心。', image: 'kai_xin.jpg', translation: 'Happy' },
    { character: '心', unicode: '5FC3', pinyin: 'xin¯', phrase: '心情', sentence: '我現在的心情很好。', image: 'xin_qing.jpg', translation: 'Heart' },
    { character: '走', unicode: '8D70', pinyin: 'zouˇ', phrase: '走路', sentence: '我喜歡走路。', image: 'zou_lu.jpg', translation: 'Walk' },
    { character: '路', unicode: '8DEF', pinyin: 'luˋ', phrase: '回家路上', sentence: '我們在回家路上。', image: 'hui_jia_lu_shang.jpg', translation: 'Road' },
    { character: '花', unicode: '82B1', pinyin: 'hua¯', phrase: '花園', sentence: '這是一個美麗的花園。', image: 'hua_yuan.jpg', translation: 'Flower' },
    { character: '田', unicode: '7530', pinyin: 'tianˊ', phrase: '農田', sentence: '我們來到了一片農田。', image: 'nong_tian.jpg', translation: 'Field' },
    { character: '看', unicode: '770B', pinyin: 'kanˋ', phrase: '看電影', sentence: '我們今天去看電影。', image: 'kan_dian_ying.jpg', translation: 'Watch' },
    { character: '見', unicode: '89C1', pinyin: 'jianˋ', phrase: '見面', sentence: '我們明天見面。', image: 'jian_mian.jpg', translation: 'Meet' },
    { character: '白', unicode: '767D', pinyin: 'baiˊ', phrase: '白雪', sentence: '外面下著白雪。', image: 'bai_xue.jpg', translation: 'White' },
    { character: '和', unicode: '548C', pinyin: 'heˊ', phrase: '和平', sentence: '我們追求和平。', image: 'he_ping.jpg', translation: 'Peace' },
    { character: '起', unicode: '8D77', pinyin: 'qiˇ', phrase: '起床', sentence: '他早上八點起床。', image: 'qi_chuang.jpg', translation: 'Get up' },
    { character: '奶', unicode: '5976', pinyin: 'naiˇ', phrase: '奶媽', sentence: '她是我的奶媽。', image: 'nai_ma.jpg', translation: 'Milk' },
    { character: '家', unicode: '5BB6', pinyin: 'jia¯', phrase: '家庭', sentence: '我們是一個幸福的家庭。', image: 'jia_ting.jpg', translation: 'Family' },
    { character: '過', unicode: '8FC7', pinyin: 'guoˋ', phrase: '過去', sentence: '過去的事情就讓它過去吧。', image: 'guo_qu.jpg', translation: 'Past' },
    { character: '兔', unicode: '5154', pinyin: 'tuˋ', phrase: '小兔子', sentence: '小兔子在跳躍。', image: 'xiao_tu_zi.jpg', translation: 'Rabbit' },
    { character: '在', unicode: '5728', pinyin: 'zaiˋ', phrase: '在學校', sentence: '他現在在學校。', image: 'zai_xue_xiao.jpg', translation: 'At' },
    { character: '了', unicode: '4E86', pinyin: 'le˙', phrase: '好了', sentence: '我洗好澡了!', image: 'liao_jie.jpg', translation: 'Used at the end of a sentence' },
    { character: '好', unicode: '597D', pinyin: 'haoˇ', phrase: '好朋友', sentence: '他是我的好朋友。', image: 'hao_peng_you.jpg', translation: 'Good' },
    { character: '多', unicode: '591A', pinyin: 'duo¯', phrase: '多雲', sentence: '今天是一個多雲的天氣。', image: 'duo_yun.jpg', translation: 'Many' },
    { character: '長', unicode: '957F', pinyin: 'zhangˇ', phrase: '長大', sentence: '他希望長大後成為一名醫生。', image: 'zhang_da.jpg', translation: 'Grow up' },
    { character: '要', unicode: '8981', pinyin: 'yaoˋ', phrase: '我要', sentence: '我要買東西。', image: 'yao_qiu.jpg', translation: 'Want' },
    { character: '水', unicode: '6C34', pinyin: 'shuiˇ', phrase: '水果', sentence: '我喜歡吃各種各樣的水果。', image: 'shui_guo.jpg', translation: 'Water' },
    { character: '光', unicode: '5149', pinyin: 'guang¯', phrase: '光明', sentence: '光明將會戰勝黑暗。', image: 'guang_ming.jpg', translation: 'Light' },
    { character: '玩', unicode: '73A9', pinyin: 'wanˊ', phrase: '玩具', sentence: '他在玩具店買了一個玩具。', image: 'wan_ju.jpg', translation: 'Play' },
    { character: '種', unicode: '79CD', pinyin: 'zhongˇ', phrase: '種子', sentence: '種子發芽了。', image: 'zhong_zi.jpg', translation: 'Kind' },
    { character: '喝', unicode: '559D', pinyin: 'he¯', phrase: '喝水', sentence: '他喝了一杯水。', image: 'he_shui.jpg', translation: 'Drink' },
    { character: '陽', unicode: '9633', pinyin: 'yangˊ', phrase: '陽光', sentence: '陽光明媚。', image: 'yang_guang.jpg', translation: 'Sunshine' },
    { character: '請', unicode: '8BF7', pinyin: 'qingˇ', phrase: '請坐', sentence: '請坐，不要客氣。', image: 'qing_zuo.jpg', translation: 'Please' },
    { character: '問', unicode: '95EE', pinyin: 'wenˋ', phrase: '問題', sentence: '你有什麼問題嗎？', image: 'wen_ti.jpg', translation: 'Ask' },
    { character: '你', unicode: '4F60', pinyin: 'niˇ', phrase: '你好', sentence: '你好，我是小明。', image: 'ni_hao.jpg', translation: 'You' },
    { character: '有', unicode: '6709', pinyin: 'youˇ', phrase: '有沒有', sentence: '你有沒有看到我的筆？', image: 'you_mei_you.jpg', translation: 'Have' },
    { character: '星', unicode: '661F', pinyin: 'xing¯', phrase: '星星', sentence: '夜空中有很多星星。', image: 'xing_xing.jpg', translation: 'Star' },
    { character: '太', unicode: '592A', pinyin: 'taiˋ', phrase: '太陽', sentence: '太陽升起了。', image: 'tai_yang.jpg', translation: 'Sun' },
    { character: '陽', unicode: '9633', pinyin: 'yangˊ', phrase: '陽光', sentence: '陽光明媚。', image: 'yang_guang.jpg', translation: 'Sunshine' },
    { character: '來', unicode: '6765', pinyin: 'laiˊ', phrase: '來自', sentence: '他來自中國。', image: 'lai_zi.jpg', translation: 'Come' },
    { character: '月', unicode: '6708', pinyin: 'yueˋ', phrase: '月亮', sentence: '今晚的月亮很圓。', image: 'yue_liang.jpg', translation: 'Moon' },
    { character: '裡', unicode: '88E4', pinyin: 'liˇ', phrase: '裡面', sentence: '我把鑰匙放在了裡面。', image: 'li_mian.jpg', translation: 'Inside' },
    { character: '海', unicode: '6D77', pinyin: 'haiˇ', phrase: '海洋', sentence: '海洋的美麗令人驚嘆。', image: 'hai_yang.jpg', translation: 'Sea' },
    { character: '亮', unicode: '4EAE', pinyin: 'liangˋ', phrase: '明亮', sentence: '房間很明亮。', image: 'ming_liang.jpg', translation: 'Bright' },
    { character: '哪', unicode: '54EA', pinyin: 'naˇ', phrase: '哪裡', sentence: '他去哪裡了？', image: 'na_li.jpg', translation: 'Where' },
    { character: '彩', unicode: '5F69', pinyin: 'caiˇ', phrase: '彩虹', sentence: '彩虹出現了。', image: 'cai_hong.jpg', translation: 'Color' },
    { character: '的', unicode: '7684', pinyin: 'de˙', phrase: '我的', sentence: '這是我的書。', image: 'wo_de.jpg', translation: 'My' },
    { character: '上', unicode: '4E0A', pinyin: 'shangˋ', phrase: '上學', sentence: '他每天都上學。', image: 'shang_xue.jpg', translation: 'Up' },
    { character: '想', unicode: '60F3', pinyin: 'xiangˇ', phrase: '想念', sentence: '我想念我的家人。', image: 'xiang_nian.jpg', translation: 'Miss' },
    { character: '爬', unicode: '722D', pinyin: 'paˊ', phrase: '爬山', sentence: '爬山對身體有益。', image: 'pa_shan.jpg', translation: 'Climb' },
    { character: '沒', unicode: '6CA1', pinyin: 'meiˊ', phrase: '沒有', sentence: '他沒有回來。', image: 'mei_you.jpg', translation: 'Not' },
    { character: '棉', unicode: '68D5', pinyin: 'mianˊ', phrase: '棉花', sentence: '這片土地適合種植棉花。', image: 'mian_hua.jpg', translation: 'Cotton' },
    { character: '下', unicode: '4E0B', pinyin: 'xiaˋ', phrase: '下雨', sentence: '外面下雨了。', image: 'xia_yu.jpg', translation: 'Under' },
    { character: '泡', unicode: '6CE1', pinyin: 'paoˋ', phrase: '泡泡', sentence: '他在玩水泡。', image: 'pao_pao.jpg', translation: 'Bubble' },
    { character: '池', unicode: '6C60', pinyin: 'chiˊ', phrase: '游泳池', sentence: '我們去游泳池游泳。', image: 'you_yong_chi.jpg', translation: 'Pool' },
    { character: '滑', unicode: '6ED1', pinyin: 'huaˊ', phrase: '滑雪', sentence: '我們去山上滑雪。', image: 'hua_xue.jpg', translation: 'Slide' },
    { character: '梯', unicode: '68AF', pinyin: 'ti¯', phrase: '樓梯', sentence: '我住在八樓，每天要爬樓梯。', image: 'lou_ti.jpg', translation: 'Stairs' },
    { character: '糖', unicode: '7CD6', pinyin: 'tangˊ', phrase: '糖果', sentence: '我喜歡吃糖果。', image: 'tang_guo.jpg', translation: 'Candy' },
    { character: '秋', unicode: '79CB', pinyin: 'qiu¯', phrase: '秋天', sentence: '秋天的葉子變黃了。', image: 'qiu_tian.jpg', translation: 'Autumn' },
    { character: '千', unicode: '5343', pinyin: 'qian¯', phrase: '千萬', sentence: '千萬不要忘記了。', image: 'qian_wan.jpg', translation: 'Thousand' },
    { character: '子', unicode: '5B50', pinyin: 'ziˇ', phrase: '母子', sentence: '他們母子倆長得很像。', image: 'xiao_hai_zi.jpg', translation: 'Child' },
    { character: '空', unicode: '7A7A', pinyin: 'kong¯', phrase: '空氣', sentence: '新鮮的空氣令人愉悅。', image: 'kong_qi.jpg', translation: 'Air' },
    { character: '說', unicode: '8BF4', pinyin: 'shuo¯', phrase: '說話', sentence: '他很會說話。', image: 'shuo_hua.jpg', translation: 'Speak' },
    { character: '早', unicode: '65E9', pinyin: 'zaoˇ', phrase: '早上', sentence: '我每天早上七點起床。', image: 'zao_shang.jpg', translation: 'Early' },
    { character: '向', unicode: '5411', pinyin: 'xiangˋ', phrase: '向前', sentence: '向前走。', image: 'xiang_qian.jpg', translation: 'Forward' },
    { character: '是', unicode: '662F', pinyin: 'shiˋ', phrase: '是不是', sentence: '你是不是聽到了聲音？', image: 'shi_bu_shi.jpg', translation: 'Is' },
    { character: '誰', unicode: '8C01', pinyin: 'sheiˊ', phrase: '誰來了', sentence: '誰來了？', image: 'shui_lai_le.jpg', translation: 'Who' },
    { character: '陪', unicode: '966A', pinyin: 'peiˊ', phrase: '陪伴', sentence: '我們一起陪伴他。', image: 'pei_ban.jpg', translation: 'Accompany' },
    { character: '他', unicode: '4ED6', pinyin: 'ta¯', phrase: '他們', sentence: '他們是我的朋友。', image: 'ta_men.jpg', translation: 'He' },
    { character: '低', unicode: '4F4E', pinyin: 'di¯', phrase: '低音', sentence: '這個音樂有一個很低的低音。', image: 'di_yin.jpg', translation: 'Low' },
    { character: '找', unicode: '627E', pinyin: 'zhaoˇ', phrase: '找工作', sentence: '他正在找工作。', image: 'zhao_gong_zuo.jpg', translation: 'Find' },
    { character: '回', unicode: '56DE', pinyin: 'huiˊ', phrase: '回家', sentence: '我已經回家了。', image: 'hui_jia.jpg', translation: 'Back' },
    { character: '山', unicode: '5C71', pinyin: 'shan¯', phrase: '大山', sentence: '他們攀登了一座大山。', image: 'da_shan.jpg', translation: 'Mountain' },
    { character: '到', unicode: '5230', pinyin: 'daoˋ', phrase: '到達', sentence: '我們終於到達目的地了。', image: 'dao_da.jpg', translation: 'Arrive' },
    { character: '我', unicode: '6211', pinyin: 'woˇ', phrase: '我們', sentence: '我們是好朋友。', image: 'wo_men.jpg', translation: 'I' },
    { character: '叫', unicode: '53EB', pinyin: 'jiaoˋ', phrase: '叫聲', sentence: '他聽到了一聲叫聲。', image: 'jiao_sheng.jpg', translation: 'Call' },
    { character: '人', unicode: '4EBA', pinyin: 'renˊ', phrase: '人類', sentence: '人類是社會的一部分。', image: 'ren_lei.jpg', translation: 'People' },
    { character: '開', unicode: '5F00', pinyin: 'kai¯', phrase: '開心', sentence: '她很開心。', image: 'kai_xin.jpg', translation: 'Happy' },
    { character: '心', unicode: '5FC3', pinyin: 'xin¯', phrase: '心情', sentence: '我現在的心情很好。', image: 'xin_qing.jpg', translation: 'Heart' },
    { character: '嗎', unicode: '541E', pinyin: 'ma˙', phrase: '好嗎    ', sentence: '你好嗎？', image: 'hao_bu_hao.jpg', translation: 'Question' },
    { character: '也', unicode: '4E5F', pinyin: 'yeˇ', phrase: '也許', sentence: '也許是我記錯了。', image: 'ye_xu.jpg', translation: 'Also' },
    { character: '笑', unicode: '7B11', pinyin: 'xiaoˋ', phrase: '笑臉', sentence: '他對著我笑了。', image: 'xiao_lian.jpg', translation: 'Laugh' },
    { character: '哈', unicode: '54C8', pinyin: 'ha¯', phrase: '哈哈', sentence: '他大聲笑了。', image: 'ha_ha.jpg', translation: 'Haha' },
    { character: '音', unicode: '97F3', pinyin: 'yin¯', phrase: '音樂', sentence: '我喜歡聽音樂。', image: 'yin_yue.jpg', translation: 'Music' },
    { character: '谷', unicode: '8C37', pinyin: 'guˇ', phrase: '山谷', sentence: '美國最有名的山谷叫大峽谷。', image: 'gu_wu.jpg', translation: 'Valley' },
    { character: '們', unicode: '4EEC', pinyin: 'men˙', phrase: '我們', sentence: '我們是好朋友。', image: 'wo_men.jpg', translation: 'We' },
    { character: '狗', unicode: '72AC', pinyin: 'gouˇ', phrase: '小狗', sentence: '小狗在跳。', translation: 'Dog' },
    { character: '冬', unicode: '51AC', pinyin: 'dong¯', phrase: '冬天', sentence: '冬天很冷。', translation: 'Winter' },
    { character: '當', unicode: '7576', pinyin: 'dang¯', phrase: '當時', sentence: '當時我不在家。', translation: 'When' },
    { character: '朋', unicode: '670B', pinyin: 'pengˊ', phrase: '朋友', sentence: '他是我的朋友。', translation: 'Friend' },
    { character: '友', unicode: '53CB', pinyin: 'youˇ', phrase: '朋友', sentence: '我們是朋友。', translation: 'Friend' },
    { character: '冷', unicode: '51B7', pinyin: 'lengˇ', phrase: '冷水', sentence: '他喝了一杯冷水。', translation: 'Cold' },
    { character: '冰', unicode: '51B0', pinyin: 'bing¯', phrase: '冰塊', sentence: '冰塊在融化。', translation: 'Ice' },
    { character: '不', unicode: '4E0D', pinyin: 'buˋ', phrase: '不好', sentence: '這個主意不好。', translation: 'Not' },
    { character: '話', unicode: '8A71', pinyin: 'huaˋ', phrase: '說話', sentence: '請大聲點說話。', translation: 'Talk' },
    { character: '急', unicode: '6025', pinyin: 'jiˊ', phrase: '急忙', sentence: '他急忙離開了。', translation: 'Urgent' },
    { character: '忙', unicode: '5FD9', pinyin: 'mangˊ', phrase: '忙碌', sentence: '他一直很忙碌。', translation: 'Busy' },
    { character: '色', unicode: '8272', pinyin: 'seˋ', phrase: '顏色', sentence: '這種顏色很漂亮。', translation: 'Color' },
    { character: '洗', unicode: '6D17', pinyin: 'xiˇ', phrase: '洗澡', sentence: '他在洗澡。', translation: 'Wash' },
    { character: '澡', unicode: '6FA1', pinyin: 'zaoˇ', phrase: '洗澡', sentence: '洗澡可以放鬆。', translation: 'Bath' },
    { character: '還', unicode: '9084', pinyin: 'haiˊ', phrase: '還好', sentence: '他還好嗎？', translation: 'Still' },
    { character: '風', unicode: '98A8', pinyin: 'feng¯', phrase: '風景', sentence: '風很大。', translation: 'Wind' },
    { character: '兒', unicode: '5152', pinyin: 'erˊ', phrase: '兒子', sentence: '他的兒子很聰明。', translation: 'Son' },
    { character: '愛', unicode: '611B', pinyin: 'aiˋ', phrase: '愛情', sentence: '愛是美好的。', translation: 'Love' },
    { character: '找', unicode: '627E', pinyin: 'zhaoˇ', phrase: '找錢', sentence: '他在找工作。', translation: 'Find' },
    { character: '春', unicode: '6625', pinyin: 'chun¯', phrase: '春天', sentence: '春天來了。', translation: 'Spring' },
    { character: '綠', unicode: '7DA0', pinyin: 'luˋ', phrase: '綠色', sentence: '草地很綠。', translation: 'Green' },
    { character: '牛', unicode: '725B', pinyin: 'niuˊ', phrase: '牛奶', sentence: '牛在吃草。', translation: 'Cow' },
    { character: '跟', unicode: '8DDF', pinyin: 'gen¯', phrase: '跟著', sentence: '跟我來。', translation: 'With' },
    { character: '直', unicode: '76F4', pinyin: 'zhiˊ', phrase: '直接', sentence: '直飛是快的。', translation: 'Direct' },
    { character: '們', unicode: '5011', pinyin: 'men˙', phrase: '我們', sentence: '我們一起去。', translation: 'We' },
    { character: '吧', unicode: '5427', pinyin: 'ba˙', phrase: '走吧', sentence: '我們走吧。', translation: 'Bar' },
    { character: '拉', unicode: '62C9', pinyin: 'la¯', phrase: '拉手', sentence: '拉著我的手。', translation: 'Pull' },
    { character: '著', unicode: '8457', pinyin: 'zhe˙', phrase: '看著', sentence: '火車駛著。', translation: 'Wearing' },
    { character: '伸', unicode: '4F38', pinyin: 'shen¯', phrase: '伸手', sentence: '伸出你的手。', translation: 'Extend' },
    { character: '手', unicode: '624B', pinyin: 'shouˇ', phrase: '手錶', sentence: '他舉起手。', translation: 'Hand' },
    { character: '抱', unicode: '62B1', pinyin: 'baoˋ', phrase: '抱歉', sentence: '抱起孩子。', translation: 'Hold' },
    { character: '得', unicode: '5F97', pinyin: 'deˊ', phrase: '得到', sentence: '我得到了它。', translation: 'Obtain' },
    { character: '溫', unicode: '6EAB', pinyin: 'wen¯', phrase: '溫度', sentence: '溫度很高。', translation: 'Warm' },
    { character: '覺', unicode: '89BA', pinyin: 'jueˊ', phrase: '感覺', sentence: '我覺得很好。', translation: 'Feel' },
    { character: '暖', unicode: '6696', pinyin: 'nuanˇ', phrase: '暖氣', sentence: '房間很暖和。', translation: 'Warm' },
    { character: '地', unicode: '5730', pinyin: 'diˋ', phrase: '地圖', sentence: '地板很乾淨。', translation: 'Ground' },
    { character: '跑', unicode: '8DD1', pinyin: 'paoˇ', phrase: '跑步', sentence: '他喜歡在公園裡跑步。', translation: 'Run' },
    { character: '聞', unicode: '805E', pinyin: 'wenˊ', phrase: '聞名', sentence: '這家餐廳很聞名。', translation: 'Smell' },
    { character: '香', unicode: '9999', pinyin: 'xiang¯', phrase: '香水', sentence: '她喜歡這款香水。', translation: 'Fragrant' },
    { character: '朵', unicode: '6735', pinyin: 'duoˇ', phrase: '花朵', sentence: '花園裡有很多花朵。', translation: 'Flower' },
    { character: '真', unicode: '771F', pinyin: 'zhen¯', phrase: '真相', sentence: '我們需要找到真相。', translation: 'Real' },
    { character: '漂', unicode: '6F02', pinyin: 'piao¯', phrase: '漂亮', sentence: '這幅畫很漂亮。', translation: 'Float' },
    { character: '亮', unicode: '4EAE', pinyin: 'liangˋ', phrase: '明亮', sentence: '房間非常亮。', translation: 'Bright' },
    { character: '原', unicode: '539F', pinyin: 'yuanˊ', phrase: '原因', sentence: '他解釋了原因。', translation: 'Original' },
    { character: '等', unicode: '7B49', pinyin: 'dengˇ', phrase: '等待', sentence: '我們在這裡等你。', translation: 'Wait' },
    { character: '介', unicode: '4EC7', pinyin: 'jieˋ', phrase: '介紹', sentence: '讓我來介紹一下自己。', translation: 'Introduce' },
    { character: '紹', unicode: '7D39', pinyin: 'shaoˋ', phrase: '介紹', sentence: '他將會介紹這個計劃。', translation: 'Introduce' },
    { character: '自', unicode: '81EA', pinyin: 'ziˋ', phrase: '自己', sentence: '他喜歡獨自旅行。', translation: 'Self' },
    { character: '己', unicode: '5DF1', pinyin: 'jiˇ', phrase: '自己', sentence: '每個人都應該照顧自己。', translation: 'Self' },
    { character: '做', unicode: '505A', pinyin: 'zuoˋ', phrase: '做飯', sentence: '今晚我來做飯。', translation: 'Do' },
    { character: '樣', unicode: '6A23', pinyin: 'yangˋ', phrase: '樣子', sentence: '這個樣子很奇怪。', translation: 'Style' },
    { character: '顏', unicode: '984F', pinyin: 'yanˊ', phrase: '顏色', sentence: '我喜歡這種顏色。', translation: 'Color' },
    { character: '送', unicode: '9001', pinyin: 'songˋ', phrase: '送禮', sentence: '他決定送一份禮物。', translation: 'Send' },
    { character: '什', unicode: '4EC0', pinyin: 'shenˊ', phrase: '什麼', sentence: '你想要什麼？', translation: 'What' },
    { character: '麼', unicode: '9EBC', pinyin: 'me˙', phrase: '什麼', sentence: '這是什麼意思？', translation: 'What' },
    { character: '呢', unicode: '5462', pinyin: 'ne˙', phrase: '呢', sentence: '你怎麼了呢？', translation: 'Particle' },
    { character: '媽', unicode: '5ABD', pinyin: 'ma¯', phrase: '媽媽', sentence: '媽媽在廚房。', translation: 'Mother' },
    { character: '生', unicode: '751F', pinyin: 'sheng¯', phrase: '生日', sentence: '明天是他的生日。', translation: 'Birth' },
    { character: '日', unicode: '65E5', pinyin: 'riˋ', phrase: '生日', sentence: '生日快樂！', translation: 'Day' },
    { character: '快', unicode: '5FEB', pinyin: 'kuaiˋ', phrase: '快樂', sentence: '大家都很快樂。', translation: 'Fast' },
    { character: '爸', unicode: '7238', pinyin: 'baˋ', phrase: '爸爸', sentence: '爸爸在工作。', translation: 'Dad' },
    { character: '姐', unicode: '59D0', pinyin: 'jieˇ', phrase: '姐姐', sentence: '姐姐正在學習。', translation: 'Older sister' },
    { character: '會', unicode: '6703', pinyin: 'huiˋ', phrase: '會議', sentence: '會議在哪裡舉行？', translation: 'Can' },
    { character: '張', unicode: '5F35', pinyin: 'zhang¯', phrase: '張紙', sentence: '這張紙是空的。', translation: 'Sheet' },
    { character: '卡', unicode: '5361', pinyin: 'kaˇ', phrase: '卡片', sentence: '他給我一張卡片。', translation: 'Card' },
    { character: '片', unicode: '7247', pinyin: 'pianˋ', phrase: '卡片', sentence: '雲朵像片片棉花。', translation: 'Slice' },
    { character: '給', unicode: '7D66', pinyin: 'geiˇ', phrase: '給我', sentence: '請給我那本書。', translation: 'Give' },
    { character: '寫', unicode: '5BEB', pinyin: 'xieˇ', phrase: '寫字', sentence: '我喜歡寫日記。', translation: 'Write' },
    { character: '畫', unicode: '756B', pinyin: 'huaˋ', phrase: '畫畫', sentence: '她正在畫畫。', translation: 'Paint' },
    { character: '外', unicode: '5916', pinyin: 'waiˋ', phrase: '外面', sentence: '外面正在下雨。', translation: 'Outside' },
    { character: '麻', unicode: '9EBB', pinyin: 'maˊ', phrase: '麻雀', sentence: '麻雀在樹上唱歌。', translation: 'Numb' },
    { character: '雀', unicode: '96C0', pinyin: 'queˋ', phrase: '麻雀', sentence: '麻雀很小巧。', translation: 'Sparrow' },
    { character: '字', unicode: '5B57', pinyin: 'ziˋ', phrase: '寫字', sentence: '學寫字很有趣。', translation: 'Character' },
    { character: '但', unicode: '4F46', pinyin: 'danˋ', phrase: '但是', sentence: '我想去，但是太遠了。', translation: 'But' },
    { character: '課', unicode: '8AB2', pinyin: 'keˋ', phrase: '課程', sentence: '今天的課很有意思。', translation: 'Class' },
    { character: '才', unicode: '624D', pinyin: 'caiˊ', phrase: '才能', sentence: '他才來不久。', translation: 'Only' },
    { character: '可', unicode: '53EF', pinyin: 'keˇ', phrase: '可以', sentence: '這件事可以做。', translation: 'Can' },
    { character: '以', unicode: '4EE5', pinyin: 'yiˇ', phrase: '可以', sentence: '可以用這個方法。', translation: 'With' },
    { character: '又', unicode: '53C8', pinyin: 'youˋ', phrase: '又來', sentence: '他又來晚了。', translation: 'Again' },
    { character: '跳', unicode: '8DF3', pinyin: 'tiaoˋ', phrase: '跳舞', sentence: '孩子們在跳舞。', translation: 'Jump' },
    { character: '停', unicode: '505C', pinyin: 'tingˊ', phrase: '停車', sentence: '車子停在那裡。', translation: 'Stop' },
    { character: '先', unicode: '5148', pinyin: 'xian¯', phrase: '先生', sentence: '你先走。', translation: 'First' },
    { character: '再', unicode: '518D', pinyin: 'zaiˋ', phrase: '再見', sentence: '我們再見面吧。', translation: 'Again' },
    { character: '窗', unicode: '7A97', pinyin: 'chuang¯', phrase: '窗戶', sentence: '窗外的風景很美。', translation: 'Window' },
    { character: '遊', unicode: '904A', pinyin: 'youˊ', phrase: '遊戲', sentence: '孩子們喜歡玩遊戲。', translation: 'Play' },
    { character: '戲', unicode: '6232', pinyin: 'xiˋ', phrase: '遊戲', sentence: '這是一款好玩的遊戲。', translation: 'Game' },
    { character: '毛', unicode: '6BDB', pinyin: 'maoˊ', phrase: '毛巾', sentence: '他用毛巾擦臉。', translation: 'Fur' },
    { character: '蟲', unicode: '87F2', pinyin: 'chongˊ', phrase: '毛蟲', sentence: '毛蟲爬上了樹。', translation: 'Insect' },
    { character: '過', unicode: '904E', pinyin: 'guoˋ', phrase: '過河', sentence: '我們必須過河。', translation: 'Cross' },
    { character: '河', unicode: '6CB3', pinyin: 'heˊ', phrase: '河流', sentence: '這條河流很寬。', translation: 'River' },
    { character: '站', unicode: '7AD9', pinyin: 'zhanˋ', phrase: '站立', sentence: '請站起來。', translation: 'Stand' },
    { character: '魚', unicode: '9B5A', pinyin: 'yuˊ', phrase: '魚類', sentence: '海裡有很多魚。', translation: 'Fish' },
    { character: '游', unicode: '6CF3', pinyin: 'youˊ', phrase: '游泳', sentence: '孩子們喜歡游泳。', translation: 'Swim' },
    { character: '哇', unicode: '54C7', pinyin: 'waˊ', phrase: '哇', sentence: '哇！這麼多魚！', translation: 'Wow' },
    { character: '青', unicode: '9752', pinyin: 'qing¯', phrase: '青蛙', sentence: '池塘裡有很多青蛙。', translation: 'Green' },
    { character: '蛙', unicode: '86D9', pinyin: 'wa¯', phrase: '青蛙', sentence: '青蛙在池塘裡唱歌。', translation: 'Frog' },
    { character: '幫', unicode: '5E6B', pinyin: 'bang¯', phrase: '幫忙', sentence: '她幫忙做家務。', translation: 'Help' },
    { character: '面', unicode: '9762', pinyin: 'mianˋ', phrase: '正面', sentence: '他站在我面前。', translation: 'Face' },
    { character: '葉', unicode: '8449', pinyin: 'yeˋ', phrase: '樹葉', sentence: '樹葉變黃了。', translation: 'Leaf' },
    { character: '坐', unicode: '5750', pinyin: 'zuoˋ', phrase: '坐下', sentence: '請坐在椅子上。', translation: 'Sit' },
    { character: '船', unicode: '8239', pinyin: 'chuanˊ', phrase: '船隻', sentence: '他們坐在船上。', translation: 'Boat' },
    { character: '推', unicode: '63A8', pinyin: 'tui¯', phrase: '推開', sentence: '請推開門。', translation: 'Push' },
    { character: '邊', unicode: '908A', pinyin: 'bian¯', phrase: '旁邊', sentence: '他站在旁邊。', translation: 'Side' },
    { character: '借', unicode: '501F', pinyin: 'jieˋ', phrase: '借書', sentence: '我去圖書館借書。', translation: 'Borrow' },
    { character: '筆', unicode: '7B46', pinyin: 'biˇ', phrase: '鉛筆', sentence: '請借我一支筆。', translation: 'Pen' },
    { character: '她', unicode: '5979', pinyin: 'ta¯', phrase: '她們', sentence: '她在學校。', translation: 'She' },
    { character: '就', unicode: '5C31', pinyin: 'jiuˋ', phrase: '就要', sentence: '他就要出發了。', translation: 'Then' },
    { character: '把', unicode: '628A', pinyin: 'baˇ', phrase: '把手', sentence: '請握緊把手。', translation: 'Handle' },
    { character: '拿', unicode: '62FF', pinyin: 'naˊ', phrase: '拿起', sentence: '他拿起書本。', translation: 'Take' },
    { character: '很', unicode: '5F88', pinyin: 'henˇ', phrase: '很好', sentence: '這道菜很好吃。', translation: 'Very' },
    { character: '都', unicode: '90FD', pinyin: 'dou¯', phrase: '都到', sentence: '他們都到了。', translation: 'All' },
    { character: '前', unicode: '524D', pinyin: 'qianˊ', phrase: '前面', sentence: '他站在前面。', translation: 'Front' },
    { character: '每', unicode: '6BCF', pinyin: 'meiˇ', phrase: '每天', sentence: '每天早上他去跑步。', translation: 'Every' },
    { character: '家', unicode: '5BB6', pinyin: 'jia¯', phrase: '家人', sentence: '家裡很溫暖。', translation: 'Home' },
    { character: '今', unicode: '4ECA', pinyin: 'jin¯', phrase: '今天', sentence: '今天是星期五。', translation: 'Today' },
    { character: '背', unicode: '80CC', pinyin: 'beiˋ', phrase: '後背', sentence: '我的背需要按摩。', translation: 'Back' },
    { character: '書', unicode: '66F8', pinyin: 'shu¯', phrase: '書本', sentence: '書架上滿是書。', translation: 'Book' },
    { character: '包', unicode: '5305', pinyin: 'bao¯', phrase: '背包', sentence: '他的包裡有很多東西。', translation: 'Bag' },
    { character: '剛', unicode: '525B', pinyin: 'gang¯', phrase: '剛好', sentence: '他剛走不久。', translation: 'Just' },
    { character: '興', unicode: '8208', pinyin: 'xingˋ', phrase: '興趣', sentence: '他對音樂很有興趣。', translation: 'Interest' },
    { character: '整', unicode: '6574', pinyin: 'zhengˇ', phrase: '整理', sentence: '整理房間很重要。', translation: 'Entire' },
    { character: '數', unicode: '6578', pinyin: 'shuˋ', phrase: '數字', sentence: '數學是學習數字的科學。', translation: 'Number' },
    { character: '完', unicode: '5B8C', pinyin: 'wanˊ', phrase: '完成', sentence: '工作已經完成。', translation: 'Complete' },
    { character: '氣', unicode: '6C23', pinyin: 'qiˋ', phrase: '氣氛', sentence: '氣氛很緊張。', translation: 'Air' },
    { character: '知', unicode: '77E5', pinyin: 'zhi¯', phrase: '知道', sentence: '我不知道答案。', translation: 'Know' },
    { character: '道', unicode: '9053', pinyin: 'daoˋ', phrase: '道路', sentence: '這條道很窄。', translation: 'Way' },
    { character: '該', unicode: '8A72', pinyin: 'gai¯', phrase: '該死', sentence: '該怎麼做呢？', translation: 'Should' },
    { character: '東', unicode: '6771', pinyin: 'dong¯', phrase: '東西', sentence: '東邊的天空很亮。', translation: 'East' },
    { character: '西', unicode: '897F', pinyin: 'xi¯', phrase: '東西', sentence: '西方文化很有趣。', translation: 'West' },
    { character: '句', unicode: '53E5', pinyin: 'juˋ', phrase: '句子', sentence: '這句話很有意思。', translation: 'Sentence' },
    { character: '冒', unicode: '5192', pinyin: 'maoˋ', phrase: '冒險', sentence: '冒險是他的愛好。', translation: 'Venture' },
    { character: '像', unicode: '50CF', pinyin: 'xiangˋ', phrase: '像素', sentence: '這張照片像真的一樣。', translation: 'Image' },
    { character: '樣', unicode: '6A23', pinyin: 'yangˋ', phrase: '樣子', sentence: '他的做事樣子很專業。', translation: 'Style' },
    { character: '越', unicode: '8D8A', pinyin: 'yueˋ', phrase: '越來越', sentence: '天氣越來越冷。', translation: 'More and more' },
    { character: '能', unicode: '80FD', pinyin: 'nengˊ', phrase: '能力', sentence: '他有很強的領導能力。', translation: 'Can' },
    { character: '對', unicode: '5C0D', pinyin: 'duiˋ', phrase: '對話', sentence: '我們需要有一次認真的對話。', translation: 'Correct' },
    { character: '兩', unicode: '5169', pinyin: 'liangˇ', phrase: '兩個', sentence: '我買了兩個蘋果。', translation: 'Two' },
    { character: '教', unicode: '6559', pinyin: 'jiao¯', phrase: '教室', sentence: '教室裡很安靜。', translation: 'Teach' },
    { character: '室', unicode: '5BA4', pinyin: 'shiˋ', phrase: '教室', sentence: '這間室內裝修很新。', translation: 'Room' },
    { character: '桌', unicode: '684C', pinyin: 'zhuo¯', phrase: '桌子', sentence: '桌子上放著很多書。', translation: 'Table' },
    { character: '意', unicode: '610F', pinyin: 'yiˋ', phrase: '意思', sentence: '他的話有特別的意思。', translation: 'Meaning' },
    { character: '思', unicode: '601D', pinyin: 'si¯', phrase: '意思', sentence: '他在思考一個難題。', translation: 'Thought' },
    { character: '個', unicode: '500B', pinyin: 'geˊ', phrase: 'ㄧ個', sentence: '每個人都有自己的選擇。', translation: 'Unit' },
    { character: '中', unicode: '4E2D', pinyin: 'zhong¯', phrase: '中間', sentence: '我們坐在教室中間。', translation: 'Middle' },
    { character: '忍', unicode: '5FCD', pinyin: 'renˇ', phrase: '忍耐', sentence: '他忍不住笑了起來。', translation: 'Endure' },
    { character: '住', unicode: '4F4F', pinyin: 'zhuˋ', phrase: '住宿', sentence: '我們在那家酒店住了一晚。', translation: 'Reside' },
    { character: '忽', unicode: '5FDD', pinyin: 'hu¯', phrase: '忽然', sentence: '忽然之間，天空變暗了。', translation: 'Suddenly' },
    { character: '然', unicode: '7136', pinyin: 'ranˊ', phrase: '忽然', sentence: '然後他就走了。', translation: 'However' },
    { character: '啊', unicode: '554A', pinyin: 'a˙', phrase: '啊', sentence: '啊，真的嗎？', translation: 'Ah' },
    { character: '畫', unicode: '756B', pinyin: 'huaˋ', phrase: '畫畫', sentence: '他喜歡畫畫。', translation: 'Paint' },
    { character: '忘', unicode: '5FD8', pinyin: 'wangˋ', phrase: '忘記', sentence: '我忘記帶鑰匙了。', translation: 'Forget' },
    { character: '用', unicode: '7528', pinyin: 'yongˋ', phrase: '使用', sentence: '請小心使用這台機器。', translation: 'Use' },
    { character: '帶', unicode: '5E26', pinyin: 'daiˋ', phrase: '帶來', sentence: '他帶來了一些好消息。', translation: 'Bring' },
    { character: '芽', unicode: '82BD', pinyin: 'yaˊ', phrase: '芽', sentence: '新芽從土裡長出來了。', translation: 'Bud' },
    { character: '打', unicode: '6253', pinyin: 'daˇ', phrase: '打電話', sentence: '他正在打電話。', translation: 'Hit' },
    { character: '雷', unicode: '96F7', pinyin: 'leiˊ', phrase: '打雷', sentence: '聽，外面在打雷。', translation: 'Thunder' },
    { character: '土', unicode: '571F', pinyin: 'tuˇ', phrase: '土地', sentence: '土地非常肥沃。', translation: 'Soil' },
    { character: '抖', unicode: '6296', pinyin: 'douˇ', phrase: '抖動', sentence: '樹葉在風中抖動。', translation: 'Shake' },
    { character: '害', unicode: '5BB3', pinyin: 'haiˋ', phrase: '害怕', sentence: '他害怕黑暗。', translation: 'Harm' },
    { character: '怕', unicode: '6015', pinyin: 'paˋ', phrase: '害怕', sentence: '不要怕，我在這裡。', translation: 'Afraid' },
    { character: '咬', unicode: '54AC', pinyin: 'yaoˇ', phrase: '咬人', sentence: '狗咬了一個人。', translation: 'Bite' },
    { character: '樹', unicode: '6A39', pinyin: 'shuˋ', phrase: '樹木', sentence: '這棵樹很大。', translation: 'Tree' },
    { character: '暖', unicode: '6696', pinyin: 'nuanˇ', phrase: '暖和', sentence: '太陽讓空氣變得暖和。', translation: 'Warm' },
    { character: '風', unicode: '98A8', pinyin: 'feng¯', phrase: '風力', sentence: '風很大，難以行走。', translation: 'Wind' },
    { character: '兒', unicode: '5152', pinyin: 'erˊ', phrase: '兒童', sentence: '公園裡有很多玩耍的兒童。', translation: 'Child' },
    { character: '勇', unicode: '52C7', pinyin: 'yongˇ', phrase: '勇敢', sentence: '他是一個勇敢的人。', translation: 'Brave' },
    { character: '敢', unicode: '6562', pinyin: 'ganˇ', phrase: '勇敢', sentence: '你敢不敢嘗試一下？', translation: 'Dare' },
    { character: '這', unicode: '9019', pinyin: 'zhe', phrase: '這些', sentence: '這是什麼？', translation: 'This' },
    { character: '棵', unicode: '68F5', pinyin: 'ke¯', phrase: '一棵樹', sentence: '院子裡種了一棵樹。', translation: 'Measure word for trees' },
    { character: '發', unicode: '767C', pinyin: 'fa¯', phrase: '發展', sentence: '公司的業務正在快速發展。', translation: 'Send out' },
    { character: '柔', unicode: '67D4', pinyin: 'rouˊ', phrase: '柔軟', sentence: '這塊布料很柔軟。', translation: 'Soft' },
    { character: '雙', unicode: '96D9', pinyin: 'shuang¯', phrase: '雙手', sentence: '他用雙手舉起了那個箱子。', translation: 'Pair' },
    { character: '聽', unicode: '807D', pinyin: 'ting¯', phrase: '聽見', sentence: '你聽見那個聲音了嗎？', translation: 'Listen' },
    { character: '鉛', unicode: '9285', pinyin: 'qian¯', phrase: '鉛筆', sentence: '他用鉛筆寫字。', translation: 'Lead' },
    { character: '橡', unicode: '6A61', pinyin: 'xiangˋ', phrase: '橡膠', sentence: '這是橡膠製的。', translation: 'Rubber' },
    { character: '皮', unicode: '76AE', pinyin: 'piˊ', phrase: '皮膚', sentence: '她的皮膚非常光滑。', translation: 'Skin' },
    { character: '常', unicode: '5E38', pinyin: 'changˊ', phrase: '常常', sentence: '他常常來這裡。', translation: 'Often' },
    { character: '錯', unicode: '932F', pinyin: 'cuoˋ', phrase: '錯誤', sentence: '這是一個常見的錯誤。', translation: 'Mistake' },
    { character: '久', unicode: '4E45', pinyin: 'jiuˇ', phrase: '長久', sentence: '我們已經認識很久了。', translation: 'Long time' },
    { character: '哭', unicode: '54ED', pinyin: 'ku¯', phrase: '哭泣', sentence: '孩子跌倒了，開始哭泣。', translation: 'Cry' },
    { character: '加', unicode: '52A0', pinyin: 'jia¯', phrase: '加油', sentence: '比賽時大家都在喊加油。', translation: 'Add' },
    { character: '油', unicode: '6CB9', pinyin: 'youˊ', phrase: '加油', sentence: '車子需要加油了。', translation: 'Oil' },
    { character: '試', unicode: '8A66', pinyin: 'shiˋ', phrase: '試驗', sentence: '他正在進行一個科學試驗。', translation: 'Try' },
    { character: '後', unicode: '5F8C', pinyin: 'houˋ', phrase: '之後', sentence: '放學後我們去公園。', translation: 'After' },
    { character: '正', unicode: '6B63', pinyin: 'zhengˋ', phrase: '正確', sentence: '他的回答是正確的。', translation: 'Correct' },
    { character: '進', unicode: '9032', pinyin: 'jinˋ', phrase: '進步', sentence: '他的學習進步很大。', translation: 'Enter' },
    { character: '步', unicode: '6B65', pinyin: 'buˋ', phrase: '進步', sentence: '一步一個腳印。', translation: 'Step' },
    { character: '需', unicode: '9700', pinyin: 'xu¯', phrase: '需要', sentence: '完成這項工作需要時間。', translation: 'Need' },
    { character: '學', unicode: '5B78', pinyin: 'xueˊ', phrase: '學習', sentence: '他在學習新技能。', translation: 'Learn' },
    { character: '擦', unicode: '64AB', pinyin: 'ca¯', phrase: '擦窗戶', sentence: '他正在擦桌子。', translation: 'Wipe' },
    { character: '確', unicode: '78BA', pinyin: 'queˋ', phrase: '確定', sentence: '我們需要確定會議的日期。', translation: 'Sure' },
    { character: '期', unicode: '671F', pinyin: 'qi¯', phrase: '期待', sentence: '我期待與你的見面。', translation: 'Period' },
    { character: '全', unicode: '5168', pinyin: 'quanˊ', phrase: '全部', sentence: '全班同學都來了。', translation: 'All' },
    { character: '班', unicode: '73ED', pinyin: 'ban¯', phrase: '班級', sentence: '他是我們班的班長。', translation: 'Class' },
    { character: '故', unicode: '6545', pinyin: 'guˋ', phrase: '故事', sentence: '她喜歡聽奶奶講故事。', translation: 'Old' },
    { character: '事', unicode: '4E8B', pinyin: 'shiˋ', phrase: '故事', sentence: '事實勝於雄辯。', translation: 'Matter' },
    { character: '記', unicode: '8A18', pinyin: 'jiˋ', phrase: '記錄', sentence: '請記下這些重要的日期。', translation: 'Record' },
    { character: '決', unicode: '6C7A', pinyin: 'jueˊ', phrase: '決定', sentence: '我們已經做出了決定。', translation: 'Decide' },
    { character: '定', unicode: '5B9A', pinyin: 'dingˋ', phrase: '決定', sentence: '位置已經定好了。', translation: 'Set' },
    { character: '狼', unicode: '72FC', pinyin: 'langˊ', phrase: '狼來了', sentence: '狼是一種野生動物。', translation: 'Wolf' },
    { character: '時', unicode: '6642', pinyin: 'shiˊ', phrase: '時間', sentence: '現在是什麼時間？', translation: 'Time' },
    { character: '間', unicode: '9593', pinyin: 'jian¯', phrase: '時間', sentence: '他在房間裡休息。', translation: 'Between' },
    { character: '段', unicode: '6BB5', pinyin: 'duanˋ', phrase: '一段時間', sentence: '他講了一段有趣的故事。', translation: 'Section' },
    { character: '動', unicode: '52D5', pinyin: 'dongˋ', phrase: '活動', sentence: '這個機器可以自動運行。', translation: 'Move' },
    { character: '物', unicode: '7269', pinyin: 'wuˋ', phrase: '物品', sentence: '他的房間裡滿是各種物品。', translation: 'Object' },
    { character: '同', unicode: '540C', pinyin: 'tongˊ', phrase: '同學', sentence: '他們是我的同學。', translation: 'Same' },
    { character: '拍', unicode: '62CD', pinyin: 'pai¯', phrase: '拍照', sentence: '她在拍照片。', translation: 'Clap' },
    { character: '臺', unicode: '81FA', pinyin: 'taiˊ', phrase: '臺灣', sentence: '臺灣是一個美麗的地方。', translation: 'Platform' },
    { character: '演', unicode: '6F14', pinyin: 'yanˇ', phrase: '演出', sentence: '他將在今晚的演出中表演。', translation: 'Perform' }
];

export const secondGrade = [
    { character: '情', unicode: '60C5', pinyin: 'qingˊ', phrase: '情感', sentence: '他的情感很豐富。', image: 'qing_gan.jpg', translation: 'Emotion' },
    { character: '候', unicode: '5019', pinyin: 'houˋ', phrase: '等候', sentence: '他在等候朋友。', image: 'deng_hou.jpg', translation: 'Wait' },
    { character: '鳥', unicode: '9CE5', pinyin: 'niaoˇ', phrase: '小鳥', sentence: '小鳥在唱歌。', image: 'xiao_niao.jpg', translation: 'Bird' },
    { character: '飛', unicode: '98DB', pinyin: 'fei¯', phrase: '飛行', sentence: '他夢見自己在飛行。', image: 'fei_xing.jpg', translation: 'Fly' },
    { character: '兔', unicode: '5154', pinyin: 'tuˋ', phrase: '兔子', sentence: '兔子跳得很快。', image: 'tu_zi.jpg', translation: 'Rabbit' },
    { character: '遠', unicode: '9060', pinyin: 'yuanˇ', phrase: '遠方', sentence: '他來自遠方。', image: 'yuan_fang.jpg', translation: 'Far' },
    { character: '慢', unicode: '6162', pinyin: 'manˋ', phrase: '慢慢', sentence: '他走得很慢。', image: 'man_man.jpg', translation: 'Slow' },
    { character: '滿', unicode: '6EFF', pinyin: 'manˇ', phrase: '滿足', sentence: '他感到很滿足。', image: 'man_zu.jpg', translation: 'Full' },
    { character: '頭', unicode: '982D', pinyin: 'touˊ', phrase: '頭髮', sentence: '她的頭髮很長。', image: 'tou_fa.jpg', translation: 'Head' },
    { character: '汗', unicode: '6C57', pinyin: 'hanˋ', phrase: '流汗', sentence: '他在運動時流汗。', image: 'liu_han.jpg', translation: 'Sweat' },
    { character: '腳', unicode: '8173', pinyin: 'jiaoˇ', phrase: '腳步', sentence: '他的腳步很輕。', image: 'jiao_bu.jpg', translation: 'Foot' },
    { character: '箏', unicode: '7B8A', pinyin: 'zheng¯', phrase: '風箏', sentence: '風箏在天空中飄揚。', image: 'feng_zheng.jpg', translation: 'Kite' },
    { character: '由', unicode: '7531', pinyin: 'youˊ', phrase: '由來', sentence: '這個故事有很長的由來。', image: 'you_lai.jpg', translation: 'From' },
    { character: '輕', unicode: '8F15', pinyin: 'qing¯', phrase: '輕輕', sentence: '她輕輕地走進房間。', image: 'qing_qing.jpg', translation: 'Light' },
    { character: '飄', unicode: '98C4', pinyin: 'piao¯', phrase: '飄逸', sentence: '她的長髮在風中飄逸。', image: 'piao_yi.jpg', translation: 'Float' },
    { character: '轉', unicode: '8F49', pinyin: 'zhuanˇ', phrase: '轉動', sentence: '他轉動著方向盤。', image: 'zhuan_dong.jpg', translation: 'Turn' },
    { character: '痠', unicode: '75E0', pinyin: 'suan¯', phrase: '痠痛', sentence: '他的肌肉感到痠痛。', image: 'suan_tong.jpg', translation: 'Sore' },
    { character: '猴', unicode: '7334', pinyin: 'houˊ', phrase: '猴子', sentence: '猴子在樹上跳來跳去。', image: 'hou_zi.jpg', translation: 'Monkey' },
    { character: '圈', unicode: '5708', pinyin: 'quan¯', phrase: '圈子', sentence: '他們在地上畫了一個圈子。', image: 'quan_zi.jpg', translation: 'Circle' },
    { character: '盪', unicode: '76EA', pinyin: 'dangˋ', phrase: '盪鞦韆', sentence: '孩子們在公園裡盪鞦韆。', image: 'dang_qiu_qian.jpg', translation: 'Swing' },
    { character: '遊', unicode: '904A', pinyin: 'youˊ', phrase: '遊戲', sentence: '孩子們喜歡玩遊戲。', image: 'you_xi.jpg', translation: 'Play' },
    { character: '戲', unicode: '6232', pinyin: 'xiˋ', phrase: '戲劇', sentence: '我們去看了一場戲劇。', image: 'xi_ju.jpg', translation: 'Drama' },
    { character: '始', unicode: '59CB', pinyin: 'shiˇ', phrase: '開始', sentence: '我們開始工作了。', image: 'kai_shi.jpg', translation: 'Start' },
    { character: '作', unicode: '4F5C', pinyin: 'zuoˋ', phrase: '工作', sentence: '他正在工作。', image: 'gong_zuo.jpg', translation: 'Work' },
    { character: '馬', unicode: '99AC', pinyin: 'maˇ', phrase: '馬匹', sentence: '牧場裡有很多馬匹。', image: 'ma_pi.jpg', translation: 'Horse' },
    { character: '耳', unicode: '8033', pinyin: 'erˇ', phrase: '耳朵', sentence: '她的耳朵很靈敏。', image: 'er_duo.jpg', translation: 'Ear' },
    { character: '卻', unicode: '537B', pinyin: 'queˋ', phrase: '卻步', sentence: '他面對困難卻步了。', image: 'que_bu.jpg', translation: 'Step back' },
    { character: '別', unicode: '5225', pinyin: 'bieˊ', phrase: '告別', sentence: '他們在車站告別。', image: 'gao_bie.jpg', translation: 'Farewell' },
    { character: '指', unicode: '6307', pinyin: 'zhiˇ', phrase: '指示', sentence: '老師在指示學生。', image: 'zhi_shi.jpg', translation: 'Point' },
    { character: '規', unicode: '898F', pinyin: 'gui¯', phrase: '規則', sentence: '比賽有一定的規則。', image: 'gui_ze.jpg', translation: 'Rule' },
    { character: '紅', unicode: '7D05', pinyin: 'hongˊ', phrase: '紅色', sentence: '她穿了一件紅色的衣服。', image: 'hong_se.jpg', translation: 'Red' },
    { character: '臉', unicode: '81C9', pinyin: 'lianˇ', phrase: '臉頰', sentence: '她的臉頰紅紅的。', image: 'lian_jia.jpg', translation: 'Face' },
    { character: '呼', unicode: '547C', pinyin: 'hu¯', phrase: '呼吸', sentence: '他在深呼吸。', image: 'hu_xi.jpg', translation: 'Breathe' },
    { character: '守', unicode: '5B88', pinyin: 'shouˇ', phrase: '守護', sentence: '他守護著家園。', image: 'shou_hu.jpg', translation: 'Guard' },
    { character: '則', unicode: '5247', pinyin: 'zeˊ', phrase: '法則', sentence: '自然有其運行的法則。', image: 'fa_ze.jpg', translation: 'Principle' },
    { character: '低', unicode: '4F4E', pinyin: 'di¯', phrase: '低頭', sentence: '他低著頭走路。', image: 'di_tou.jpg', translation: 'Low' },
    { character: '身', unicode: '8EAB', pinyin: 'shen¯', phrase: '身體', sentence: '他有健康的身體。', image: 'shen_ti.jpg', translation: 'Body' },
    { character: '次', unicode: '6B21', pinyin: 'ciˋ', phrase: '次數', sentence: '我們要計算次數。', image: 'ci_shu.jpg', translation: 'Time' },
    { character: '踩', unicode: '8E29', pinyin: 'caiˇ', phrase: '踩踏', sentence: '他不小心踩到了花。', image: 'cai_ta.jpg', translation: 'Step' },
    { character: '影', unicode: '5F71', pinyin: 'yingˇ', phrase: '影子', sentence: '樹下有一個影子。', image: 'ying_zi.jpg', translation: 'Shadow' },
    { character: '犯', unicode: '72AF', pinyin: 'fanˋ', phrase: '犯錯', sentence: '他不小心犯了錯。', image: 'fan_cuo.jpg', translation: 'Commit' },
    { character: '謝', unicode: '8B1D', pinyin: 'xieˋ', phrase: '謝謝', sentence: '他感激地說謝謝。', image: 'xie_xie.jpg', translation: 'Thank' },
    { character: '重', unicode: '91CD', pinyin: 'zhongˋ', phrase: '重要', sentence: '這是一件重要的事情。', image: 'zhong_yao.jpg', translation: 'Important' },
    { character: '新', unicode: '65B0', pinyin: 'xin¯', phrase: '新年', sentence: '新年快樂！', image: 'xin_nian.jpg', translation: 'New' },
    { character: '便', unicode: '4FBF', pinyin: 'bianˋ', phrase: '方便', sentence: '這個工具很方便。', image: 'fang_bian.jpg', translation: 'Convenient' },
    { character: '聽', unicode: '807D', pinyin: 'ting¯', phrase: '聽音樂', sentence: '他喜歡聽音樂。', image: 'ting_yin_yue.jpg', translation: 'Listen' },
    { character: '點', unicode: '9EDE', pinyin: 'dianˇ', phrase: '點心', sentence: '他在吃點心。', image: 'dian_xin.jpg', translation: 'Point' },
    { character: '言', unicode: '8A00', pinyin: 'yanˊ', phrase: '言語', sentence: '他的言語很有智慧。', image: 'yan_yu.jpg', translation: 'Speech' },
    { character: '語', unicode: '8A9E', pinyin: 'yuˇ', phrase: '語言', sentence: '他能說多種語言。', image: 'yu_yan.jpg', translation: 'Language' },
    { character: '聲', unicode: '8072', pinyin: 'sheng¯', phrase: '聲音', sentence: '她的聲音很好聽。', image: 'sheng_yin.jpg', translation: 'Sound' },
    { character: '容', unicode: '5BB9', pinyin: 'rongˊ', phrase: '容貌', sentence: '她的容貌很美。', image: 'rong_mao.jpg', translation: 'Appearance' },
    { character: '易', unicode: '6613', pinyin: 'yiˋ', phrase: '容易', sentence: '這道題目很容易。', image: 'rong_yi.jpg', translation: 'Easy' },
    { character: '被', unicode: '88AB', pinyin: 'beiˋ', phrase: '被動', sentence: '他在被動地接受。', image: 'bei_dong.jpg', translation: 'Passive' },
    { character: '邊', unicode: '908A', pinyin: 'bian¯', phrase: '邊緣', sentence: '他站在邊緣。', image: 'bian_yuan.jpg', translation: 'Edge' },
    { character: '躲', unicode: '8EB2', pinyin: 'duoˇ', phrase: '躲藏', sentence: '他躲在樹後面。', image: 'duo_cang.jpg', translation: 'Hide' },
    { character: '為', unicode: '70BA', pinyin: 'weiˋ', phrase: '為什麼', sentence: '他為什麼這樣做？', image: 'wei_shen_me.jpg', translation: 'For' },
    { character: '歡', unicode: '6B61', pinyin: 'huan¯', phrase: '歡樂', sentence: '節日帶來了歡樂。', image: 'huan_le.jpg', translation: 'Joy' },
    { character: '趣', unicode: '8DA3', pinyin: 'quˋ', phrase: '興趣', sentence: '他的興趣是讀書。', image: 'xing_qu.jpg', translation: 'Interest' },
    { character: '呀', unicode: '5440', pinyin: 'ya¯', phrase: '哎呀', sentence: '哎呀！你嚇到我了！', image: 'ya.jpg', translation: 'Ah' },
    { character: '遵', unicode: '9075', pinyin: 'zun¯', phrase: '遵守', sentence: '我們應該遵守規則。', image: 'zun_shou.jpg', translation: 'Follow' },
    { character: '隨', unicode: '96A8', pinyin: 'suiˊ', phrase: '隨意', sentence: '請隨意坐下。', image: 'sui_yi.jpg', translation: 'Follow' },
    { character: '觀', unicode: '89C0', pinyin: 'guan¯', phrase: '觀察', sentence: '他在觀察星星。', image: 'guan_cha.jpg', translation: 'Observe' },
    { character: '察', unicode: '5BDF', pinyin: 'chaˊ', phrase: '觀察', sentence: '他在觀察星星。', image: 'guan_cha.jpg', translation: 'Inspect' },
    { character: '呱', unicode: '5471', pinyin: 'gua¯', phrase: '呱呱', sentence: '青蛙呱呱叫。', image: 'gua_gua.jpg', translation: 'Quack' },
    { character: '只', unicode: '53EA', pinyin: 'zhiˇ', phrase: '只要', sentence: '只要努力，就會成功。', image: 'zhi_yao.jpg', translation: 'Only' },
    { character: '影', unicode: '5F71', pinyin: 'yingˇ', phrase: '影子', sentence: '樹下有一個影子。', image: 'ying_zi.jpg', translation: 'Shadow' },
    { character: '猜', unicode: '731C', pinyin: 'cai¯', phrase: '猜謎', sentence: '他在猜謎語。', image: 'cai_mi_yu.jpg', translation: 'Guess' },
    { character: '靠', unicode: '9760', pinyin: 'kaoˋ', phrase: '靠近', sentence: '請不要靠近火源。', image: 'kao_jin.jpg', translation: 'Near' },
    { character: '近', unicode: '8FD1', pinyin: 'jinˋ', phrase: '接近', sentence: '他們接近了山頂。', image: 'jie_jin.jpg', translation: 'Close' },
    { character: '划', unicode: '5283', pinyin: 'huaˊ', phrase: '划船', sentence: '他們在河上划船。', image: 'hua_chuan.jpg', translation: 'Row' },
    { character: '抓', unicode: '6293', pinyin: 'zhua¯', phrase: '抓住', sentence: '他抓住了繩子。', image: 'zhua_zhu.jpg', translation: 'Grab' },
    { character: '如', unicode: '5982', pinyin: 'ruˊ', phrase: '如果', sentence: '如果下雨，我們就不去了。', image: 'ru_guo.jpg', translation: 'If' },
    { character: '果', unicode: '679C', pinyin: 'guoˇ', phrase: '果實', sentence: '這棵樹結了很多果實。', image: 'guo_shi.jpg', translation: 'Fruit' },
    { character: '乖', unicode: '4E56', pinyin: 'guai¯', phrase: '乖孩子', sentence: '他是個乖孩子。', image: 'guai_haizi.jpg', translation: 'Obedient' },
    { character: '偷', unicode: '5077', pinyin: 'tou¯', phrase: '偷東西', sentence: '小偷在偷東西。', image: 'tou_dongxi.jpg', translation: 'Steal' },
    { character: '腦', unicode: '8166', pinyin: 'naoˇ', phrase: '腦袋', sentence: '他在用腦袋思考。', image: 'nao_dai.jpg', translation: 'Brain' },
    { character: '袋', unicode: '888B', pinyin: 'daiˋ', phrase: '袋子', sentence: '他帶了一個大袋子。', image: 'dai_zi.jpg', translation: 'Bag' },
    { character: '瓜', unicode: '74DC', pinyin: 'gua¯', phrase: '瓜果', sentence: '這些瓜果很新鮮。', image: 'gua_guo.jpg', translation: 'Melon' },
    { character: '證', unicode: '8B49', pinyin: 'zhengˋ', phrase: '證明', sentence: '他提供了證明。', image: 'zheng_ming.jpg', translation: 'Prove' },
    { character: '明', unicode: '660E', pinyin: 'mingˊ', phrase: '明天', sentence: '明天見！', image: 'ming_tian.jpg', translation: 'Bright' },
    { character: '頂', unicode: '9802', pinyin: 'dingˇ', phrase: '山頂', sentence: '我們爬到了山頂。', image: 'shan_ding.jpg', translation: 'Top' },
    { character: '蝦', unicode: '8766', pinyin: 'xia¯', phrase: '蝦子', sentence: '我喜歡吃蝦子。', image: 'xia_zi.jpg', translation: 'Shrimp' },
    { character: '蟆', unicode: '87C6', pinyin: 'maˇ', phrase: '癩蛤蟆', sentence: '癩蛤蟆在池塘裡。', image: 'lai_ha_ma.jpg', translation: 'Toad' },
    { character: '撥', unicode: '64A5', pinyin: 'bo¯', phrase: '撥動', sentence: '他撥動了琴弦。', image: 'bo_dong.jpg', translation: 'Dial' },
    { character: '擔', unicode: '64D4', pinyin: 'dan¯', phrase: '擔心', sentence: '媽媽很擔心我。', image: 'dan_xin.jpg', translation: 'Worry' },
    { character: '沙', unicode: '6C99', pinyin: 'sha¯', phrase: '沙灘', sentence: '孩子們在沙灘上玩耍。', image: 'sha_tan.jpg', translation: 'Sand' },
    { character: '海', unicode: '6D77', pinyin: 'haiˇ', phrase: '海洋', sentence: '海洋非常廣闊。', image: 'hai_yang.jpg', translation: 'Sea' },
    { character: '退', unicode: '9000', pinyin: 'tuiˋ', phrase: '退後', sentence: '他向後退了幾步。', image: 'tui_hou.jpg', translation: 'Retreat' },
    { character: '洞', unicode: '6D1E', pinyin: 'dongˋ', phrase: '山洞', sentence: '我們在山洞裡探險。', image: 'shan_dong.jpg', translation: 'Cave' },
    { character: '愛', unicode: '611B', pinyin: 'aiˋ', phrase: '愛情', sentence: '愛情是美好的。', image: 'ai_qing.jpg', translation: 'Love' },
    { character: '注', unicode: '6CE8', pinyin: 'zhuˋ', phrase: '注意', sentence: '請注意安全。', image: 'zhu_yi.jpg', translation: 'Pay attention' },
    { character: '怎', unicode: '600E', pinyin: 'zenˇ', phrase: '怎麼', sentence: '這是怎麼回事？', image: 'zen_me.jpg', translation: 'How' },
    { character: '妹', unicode: '59B9', pinyin: 'meiˋ', phrase: '妹妹', sentence: '她是我的妹妹。', image: 'mei_mei.jpg', translation: 'Younger sister' },
    { character: '夕', unicode: '5915', pinyin: 'xi¯', phrase: '夕陽', sentence: '夕陽西下。', image: 'xi_yang.jpg', translation: 'Evening' },
    { character: '照', unicode: '7167', pinyin: 'zhaoˋ', phrase: '照相', sentence: '我們在公園裡照相。', image: 'zhao_xiang.jpg', translation: 'Photo' },
    { character: '閃', unicode: '9583', pinyin: 'shanˇ', phrase: '閃電', sentence: '天空中有閃電。', image: 'shan_dian.jpg', translation: 'Flash' },
    { character: '發', unicode: '767C', pinyin: 'fa¯', phrase: '發現', sentence: '我發現了一個秘密。', image: 'fa_xian.jpg', translation: 'Discover' },
    { character: '丫', unicode: '4E2B', pinyin: 'ya¯', phrase: '丫頭', sentence: '那個丫頭很可愛。', image: 'ya_tou.jpg', translation: 'Girl' },
    { character: '留', unicode: '7559', pinyin: 'liuˊ', phrase: '留學', sentence: '他去國外留學了。', image: 'liu_xue.jpg', translation: 'Stay' },
    { character: '印', unicode: '5370', pinyin: 'yinˋ', phrase: '印象', sentence: '她給我留下了深刻的印象。', image: 'yin_xiang.jpg', translation: 'Impression' },
    { character: '挖', unicode: '6316', pinyin: 'wa¯', phrase: '挖洞', sentence: '他在地上挖洞。', image: 'wa_dong.jpg', translation: 'Dig' },
    { character: '美', unicode: '7F8E', pinyin: 'meiˇ', phrase: '美麗', sentence: '這裡的風景很美麗。', image: 'mei_li.jpg', translation: 'Beautiful' },
    { character: '麗', unicode: '9E97', pinyin: 'liˋ', phrase: '秀麗', sentence: '這座山很秀麗。', image: 'xiu_li.jpg', translation: 'Beautiful' },
    { character: '灘', unicode: '7058', pinyin: 'tan¯', phrase: '海灘', sentence: '我們在海灘上玩耍。', image: 'hai_tan.jpg', translation: 'Beach' },
    { character: '螃', unicode: '8782', pinyin: 'pangˊ', phrase: '螃蟹', sentence: '螃蟹橫著走。', image: 'pang_xie.jpg', translation: 'Crab' },
    { character: '蟹', unicode: '87F9', pinyin: 'xieˋ', phrase: '螃蟹', sentence: '螃蟹橫著走。', image: 'pang_xie.jpg', translation: 'Crab' },
    { character: '橫', unicode: '6A6B', pinyin: 'hengˊ', phrase: '橫跨', sentence: '這座橋橫跨河流。', image: 'heng_kua.jpg', translation: 'Across' },
    { character: '晴', unicode: '6674', pinyin: 'qingˊ', phrase: '晴天', sentence: '今天天氣晴朗。', image: 'qing_tian.jpg', translation: 'Sunny' },
    { character: '放', unicode: '653E', pinyin: 'fangˋ', phrase: '放學', sentence: '孩子們放學了。', image: 'fang_xue.jpg', translation: 'Release' },
    { character: '奶', unicode: '5976', pinyin: 'naiˇ', phrase: '牛奶', sentence: '每天早上喝牛奶。', image: 'niu_nai.jpg', translation: 'Milk' },
    { character: '晚', unicode: '665A', pinyin: 'wanˇ', phrase: '晚上', sentence: '晚上我們去散步。', image: 'wan_shang.jpg', translation: 'Evening' },
    { character: '飯', unicode: '98EF', pinyin: 'fanˋ', phrase: '晚飯', sentence: '我們一起吃晚飯。', image: 'wan_fan.jpg', translation: 'Meal' },
    { character: '散', unicode: '6563', pinyin: 'sanˋ', phrase: '散步', sentence: '他喜歡在公園散步。', image: 'san_bu.jpg', translation: 'Disperse' },
    { character: '穿', unicode: '7A7F', pinyin: 'chuan¯', phrase: '穿衣服', sentence: '她正在穿衣服。', image: 'chuan_yi_fu.jpg', translation: 'Wear' },
    { character: '屋', unicode: '5C4B', pinyin: 'wu¯', phrase: '房屋', sentence: '這是一間古老的房屋。', image: 'fang_wu.jpg', translation: 'House' },
    { character: '竹', unicode: '7AF9', pinyin: 'zhuˊ', phrase: '竹子', sentence: '熊貓喜歡吃竹子。', image: 'zhu_zi.jpg', translation: 'Bamboo' },
    { character: '林', unicode: '6797', pinyin: 'linˊ', phrase: '森林', sentence: '我們在森林裡探險。', image: 'sen_lin.jpg', translation: 'Forest' },
    { character: '旁', unicode: '65C1', pinyin: 'pangˊ', phrase: '旁邊', sentence: '他坐在我旁邊。', image: 'pang_bian.jpg', translation: 'Beside' },
    { character: '暗', unicode: '6697', pinyin: 'anˋ', phrase: '黑暗', sentence: '房間裡很黑暗。', image: 'hei_an.jpg', translation: 'Dark' },
    { character: '眼', unicode: '773C', pinyin: 'yanˇ', phrase: '眼睛', sentence: '她的眼睛很漂亮。', image: 'yan_jing.jpg', translation: 'Eye' },
    { character: '睛', unicode: '775B', pinyin: 'jing¯', phrase: '眼睛', sentence: '她的眼睛很明亮。', image: 'yan_jing.jpg', translation: 'Eye' },
    { character: '那', unicode: '90A3', pinyin: 'naˋ', phrase: '那邊', sentence: '那邊有一座山。', image: 'na_bian.jpg', translation: 'That' },
    { character: '成', unicode: '6210', pinyin: 'chengˊ', phrase: '成就', sentence: '他取得了很大的成就。', image: 'cheng_jiu.jpg', translation: 'Become' },
    { character: '雲', unicode: '96F2', pinyin: 'yunˊ', phrase: '白雲', sentence: '天空中的白雲很美。', image: 'bai_yun.jpg', translation: 'Cloud' },
    { character: '顆', unicode: '9846', pinyin: 'ke¯', phrase: '顆粒', sentence: '這些顆粒很細小。', image: 'ke_li.jpg', translation: 'Grain' },
    { character: '叢', unicode: '53E2', pinyin: 'congˊ', phrase: '草叢', sentence: '兔子躲在草叢裡。', image: 'cao_cong.jpg', translation: 'Bush' },
    { character: '盡', unicode: '76E1', pinyin: 'jinˋ', phrase: '盡力', sentence: '他盡力完成了任務。', image: 'jin_li.jpg', translation: 'Exhaust' },
    { character: '溪', unicode: '6EAA', pinyin: 'xi¯', phrase: '小溪', sentence: '我們在小溪邊玩耍。', image: 'xiao_xi.jpg', translation: 'Stream' },
    { character: '聚', unicode: '805A', pinyin: 'juˋ', phrase: '聚會', sentence: '我們舉行了一次聚會。', image: 'ju_hui.jpg', translation: 'Gather' },
    { character: '戶', unicode: '6236', pinyin: 'huˋ', phrase: '戶外', sentence: '我們喜歡戶外活動。', image: 'hu_wai.jpg', translation: 'Household' },
    { character: '育', unicode: '80B2', pinyin: 'yuˋ', phrase: '教育', sentence: '教育孩子是很重要的。', image: 'jiao_yu.jpg', translation: 'Raise' },
    { character: '奇', unicode: '5947', pinyin: 'qiˊ', phrase: '奇怪', sentence: '這個現象很奇怪。', image: 'qi_guai.jpg', translation: 'Strange' },
    { character: '帶', unicode: '5E36', pinyin: 'daiˋ', phrase: '帶子', sentence: '他繫上了帶子。', image: 'dai_zi.jpg', translation: 'Belt' },
    { character: '筒', unicode: '7B52', pinyin: 'tongˇ', phrase: '竹筒', sentence: '他用竹筒喝水。', image: 'zhu_tong.jpg', translation: 'Tube' },
    { character: '味', unicode: '5473', pinyin: 'weiˋ', phrase: '味道', sentence: '這道菜的味道很好。', image: 'wei_dao.jpg', translation: 'Taste' },
    { character: '祖', unicode: '7956', pinyin: 'zuˇ', phrase: '祖先', sentence: '我們尊敬祖先。', image: 'zu_xian.jpg', translation: 'Ancestor' },
    { character: '盒', unicode: '76D2', pinyin: 'heˊ', phrase: '盒子', sentence: '他打開了盒子。', image: 'he_zi.jpg', translation: 'Box' },
    { character: '客', unicode: '5BA2', pinyin: 'keˋ', phrase: '客人', sentence: '他們是我們的客人。', image: 'ke_ren.jpg', translation: 'Guest' },
    { character: '清', unicode: '6E05', pinyin: 'qing¯', phrase: '清水', sentence: '這裡的清水很乾淨。', image: 'qing_shui.jpg', translation: 'Clear' },
    { character: '節', unicode: '7BC0', pinyin: 'jieˊ', phrase: '節日', sentence: '我們一起慶祝節日。', image: 'jie_ri.jpg', translation: 'Festival' },
    { character: '保', unicode: '4FDD', pinyin: 'baoˇ', phrase: '保護', sentence: '我們要保護環境。', image: 'bao_hu.jpg', translation: 'Protect' },
    { character: '平', unicode: '5E73', pinyin: 'pingˊ', phrase: '平靜', sentence: '湖面很平靜。', image: 'ping_jing.jpg', translation: 'Flat' },
    { character: '安', unicode: '5B89', pinyin: 'an¯', phrase: '安全', sentence: '請注意安全。', image: 'an_quan.jpg', translation: 'Safe' },
    { character: '南', unicode: '5357', pinyin: 'nanˊ', phrase: '南方', sentence: '南方的氣候很溫暖。', image: 'nan_fang.jpg', translation: 'South' },
    { character: '活', unicode: '6D3B', pinyin: 'huoˊ', phrase: '生活', sentence: '他們的生活很幸福。', image: 'sheng_huo.jpg', translation: 'Live' },
    { character: '剛', unicode: '525B', pinyin: 'gang¯', phrase: '剛才', sentence: '他剛才來過這裡。', image: 'gang_cai.jpg', translation: 'Just' },
    { character: '校', unicode: '6821', pinyin: 'xiaoˋ', phrase: '學校', sentence: '學生們在學校上課。', image: 'xue_xiao.jpg', translation: 'School' },
    { character: '膜', unicode: '819C', pinyin: 'moˊ', phrase: '薄膜', sentence: '這層薄膜很薄。', image: 'bo_mo.jpg', translation: 'Membrane' },
    { character: '艾', unicode: '827E', pinyin: 'aiˋ', phrase: '艾草', sentence: '艾草有很多用途。', image: 'ai_cao.jpg', translation: 'Mugwort' },
    { character: '粄', unicode: '7C84', pinyin: 'banˇ', phrase: '粿粄', sentence: '這是一道美味的粿粄。', image: 'guo_ban.jpg', translation: 'Rice cake' },
    { character: '捲', unicode: '6372', pinyin: 'juanˇ', phrase: '捲起', sentence: '他捲起袖子。', image: 'juan_qi.jpg', translation: 'Roll' },
    { character: '食', unicode: '98DF', pinyin: 'shiˊ', phrase: '食物', sentence: '這些食物很美味。', image: 'shi_wu.jpg', translation: 'Food' },
    { character: '分', unicode: '5206', pinyin: 'fen¯', phrase: '分享', sentence: '他們在分享食物。', image: 'fen_xiang.jpg', translation: 'Share' },
    { character: '享', unicode: '4EAB', pinyin: 'xiangˇ', phrase: '享受', sentence: '她在享受音樂。', image: 'xiang_shou.jpg', translation: 'Enjoy' },
    { character: '圓', unicode: '5713', pinyin: 'yuanˊ', phrase: '圓形', sentence: '這是一個圓形的物體。', image: 'yuan_xing.jpg', translation: 'Round' },
    { character: '形', unicode: '5F62', pinyin: 'xingˊ', phrase: '形狀', sentence: '這個形狀很奇特。', image: 'xing_zhuang.jpg', translation: 'Shape' },
    { character: '米', unicode: '7C73', pinyin: 'miˇ', phrase: '大米', sentence: '我們每天都吃大米。', image: 'da_mi.jpg', translation: 'Rice' },
    { character: '軟', unicode: '8EDF', pinyin: 'ruanˇ', phrase: '柔軟', sentence: '這張床很柔軟。', image: 'rou_ruan.jpg', translation: 'Soft' },
    { character: '搶', unicode: '6436', pinyin: 'qiangˇ', phrase: '搶劫', sentence: '他們進行了搶劫。', image: 'qiang_jie.jpg', translation: 'Rob' },
    { character: '材', unicode: '6750', pinyin: 'caiˊ', phrase: '材料', sentence: '這些是建築材料。', image: 'jian_zhu_cai_liao.jpg', translation: 'Material' },
    { character: '蝦', unicode: '8766', pinyin: 'xia¯', phrase: '蝦子', sentence: '我喜歡吃蝦子。', image: 'xia_zi.jpg', translation: 'Shrimp' },
    { character: '線', unicode: '7DDA', pinyin: 'xianˋ', phrase: '線條', sentence: '這幅畫的線條很優美。', image: 'xian_tiao.jpg', translation: 'Line' },
    { character: '各', unicode: '5404', pinyin: 'geˋ', phrase: '各種', sentence: '市場上有各種水果。', image: 'ge_zhong.jpg', translation: 'Each' },
    { character: '種', unicode: '7A2E', pinyin: 'zhongˇ', phrase: '種類', sentence: '這裡有很多種類的花。', image: 'zhong_lei.jpg', translation: 'Type' },
    { character: '菜', unicode: '83DC', pinyin: 'caiˋ', phrase: '蔬菜', sentence: '多吃蔬菜對健康有益。', image: 'shu_cai.jpg', translation: 'Vegetable' },
    { character: '接', unicode: '63A5', pinyin: 'jie¯', phrase: '接電話', sentence: '他正在接電話。', image: 'jie_dian_hua.jpg', translation: 'Receive' },
    { character: '老', unicode: '8001', pinyin: 'laoˇ', phrase: '老師', sentence: '她是一位好老師。', image: 'lao_shi.jpg', translation: 'Old' },
    { character: '師', unicode: '5E2B', pinyin: 'shi¯', phrase: '師傅', sentence: '他是一位廚師傅。', image: 'chu_shi_fu.jpg', translation: 'Teacher' },
    { character: '更', unicode: '66F4', pinyin: 'gengˋ', phrase: '更新', sentence: '我們需要更新軟件。', image: 'geng_xin.jpg', translation: 'More' },
    { character: '紙', unicode: '7D19', pinyin: 'zhiˇ', phrase: '紙張', sentence: '請給我一張紙。', image: 'zhi_zhang.jpg', translation: 'Paper' },
    { character: '變', unicode: '8B8A', pinyin: 'bianˋ', phrase: '變化', sentence: '天氣有很大的變化。', image: 'bian_hua.jpg', translation: 'Change' },
    { character: '舉', unicode: '8209', pinyin: 'juˇ', phrase: '舉手', sentence: '請舉手發言。', image: 'ju_shou.jpg', translation: 'Raise' },
    { character: '涼', unicode: '6DBC', pinyin: 'liangˊ', phrase: '涼快', sentence: '今天的天氣很涼快。', image: 'liang_kuai.jpg', translation: 'Cool' },
    { character: '黃', unicode: '9EC3', pinyin: 'huangˊ', phrase: '黃色', sentence: '她喜歡黃色的花。', image: 'huang_se.jpg', translation: 'Yellow' },
    { character: '沖', unicode: '6C96', pinyin: 'chong¯', phrase: '沖水', sentence: '請記得沖水。', image: 'chong_shui.jpg', translation: 'Flush' },
    { character: '哪', unicode: '54EA', pinyin: 'naˇ', phrase: '哪裡', sentence: '你住在哪裡？', image: 'na_li.jpg', translation: 'Where' },
    { character: '粒', unicode: '7C92', pinyin: 'liˋ', phrase: '米粒', sentence: '這些米粒很小。', image: 'mi_li.jpg', translation: 'Grain' },
    { character: '熱', unicode: '71B1', pinyin: 'reˋ', phrase: '熱水', sentence: '冬天喝點熱水。', image: 're_shui.jpg', translation: 'Hot' },
    { character: '浴', unicode: '6D74', pinyin: 'yuˋ', phrase: '洗浴', sentence: '我每天都洗浴。', image: 'xi_yu.jpg', translation: 'Bath' },
    { character: '蒸', unicode: '84B8', pinyin: 'zheng¯', phrase: '蒸汽', sentence: '廚房裡有很多蒸汽。', image: 'zheng_qi.jpg', translation: 'Steam' },
    { character: '胖', unicode: '80D6', pinyin: 'pangˋ', phrase: '胖子', sentence: '他是一個胖子。', image: 'pang_zi.jpg', translation: 'Fat' },
    { character: '名', unicode: '540D', pinyin: 'mingˊ', phrase: '名字', sentence: '你的名字是什麼？', image: 'ming_zi.jpg', translation: 'Name' },
    { character: '苔', unicode: '82D4', pinyin: 'taiˊ', phrase: '苔蘚', sentence: '石頭上長滿了苔蘚。', image: 'tai_xian.jpg', translation: 'Moss' },
    { character: '蛋', unicode: '86CB', pinyin: 'danˋ', phrase: '雞蛋', sentence: '早餐有雞蛋和牛奶。', image: 'ji_dan.jpg', translation: 'Egg' },
    { character: '通', unicode: '901A', pinyin: 'tong¯', phrase: '通過', sentence: '他通過了考試。', image: 'tong_guo.jpg', translation: 'Pass' },
    { character: '細', unicode: '7D30', pinyin: 'xiˋ', phrase: '細心', sentence: '她是一個很細心的人。', image: 'xi_xin.jpg', translation: 'Thin' },
    { character: '淡', unicode: '6DE1', pinyin: 'danˋ', phrase: '淡水', sentence: '這裡的湖水是淡水。', image: 'dan_shui.jpg', translation: 'Light' },
    { character: '最', unicode: '6700', pinyin: 'zuiˋ', phrase: '最好', sentence: '他是我最好的朋友。', image: 'zui_hao.jpg', translation: 'Most' },
    { character: '緊', unicode: '7DCA', pinyin: 'jinˇ', phrase: '緊張', sentence: '他看起來很緊張。', image: 'jin_zhang.jpg', translation: 'Tight' },
    { character: '蘿', unicode: '863F', pinyin: 'luoˊ', phrase: '蘿蔔', sentence: '蘿蔔有很多種顏色。', image: 'luo_bo.jpg', translation: 'Radish' },
    { character: '蔔', unicode: '84D2', pinyin: 'bo¯', phrase: '蘿蔔', sentence: '蘿蔔有很多種顏色。', image: 'luo_bo.jpg', translation: 'Radish' },
    { character: '蔬', unicode: '852C', pinyin: 'shu¯', phrase: '蔬菜', sentence: '多吃蔬菜對健康有益。', image: 'shu_cai.jpg', translation: 'Vegetable' },
    { character: '黏', unicode: '9ECF', pinyin: 'nianˊ', phrase: '黏糊', sentence: '這些糖果很黏糊。', image: 'nian_hu.jpg', translation: 'Sticky' },
    { character: '減', unicode: '6E1B', pinyin: 'jianˇ', phrase: '減少', sentence: '我們需要減少浪費。', image: 'jian_shao.jpg', translation: 'Reduce' },
    { character: '表', unicode: '8868', pinyin: 'biaoˇ', phrase: '表現', sentence: '他的表現很好。', image: 'biao_xian.jpg', translation: 'Watch' },
    { character: '弟', unicode: '5F1F', pinyin: 'diˋ', phrase: '弟弟', sentence: '我有一個弟弟。', image: 'di_di.jpg', translation: 'Younger brother' },
    { character: '讀', unicode: '8B80', pinyin: 'duˊ', phrase: '讀書', sentence: '他喜歡讀書。', image: 'du_shu.jpg', translation: 'Read' },
    { character: '認', unicode: '8A8D', pinyin: 'renˋ', phrase: '認識', sentence: '我們認識了很多新朋友。', image: 'ren_shi.jpg', translation: 'Recognize' },
    { character: '識', unicode: '8B58', pinyin: 'shiˋ', phrase: '知識', sentence: '知識改變命運。', image: 'zhi_shi.jpg', translation: 'Knowledge' },
    { character: '謎', unicode: '8B0E', pinyin: 'miˊ', phrase: '謎語', sentence: '他喜歡猜謎語。', image: 'mi_yu.jpg', translation: 'Riddle' },
    { character: '答', unicode: '7B54', pinyin: 'da¯', phrase: '回答', sentence: '他回答了老師的問題。', image: 'hui_da.jpg', translation: 'Answer' },
    { character: '搖', unicode: '6416', pinyin: 'yaoˊ', phrase: '搖動', sentence: '他搖動著樹枝。', image: 'yao_dong.jpg', translation: 'Shake' },
    { character: '百', unicode: '767E', pinyin: 'baiˇ', phrase: '百姓', sentence: '百姓生活安康。', image: 'bai_xing.jpg', translation: 'Hundred' },
    { character: '哥', unicode: '54E5', pinyin: 'ge¯', phrase: '哥哥', sentence: '他是我的哥哥。', image: 'ge_ge.jpg', translation: 'Older brother' },
    { character: '題', unicode: '984C', pinyin: 'tiˊ', phrase: '問題', sentence: '這是一個有趣的問題。', image: 'wen_ti.jpg', translation: 'Question' },
    { character: '趕', unicode: '8D95', pinyin: 'ganˇ', phrase: '趕時間', sentence: '他們在趕時間。', image: 'gan_shi_jian.jpg', translation: 'Catch up' },
    { character: '王', unicode: '738B', pinyin: 'wangˊ', phrase: '國王', sentence: '國王統治這個國家。', image: 'guo_wang.jpg', translation: 'King' },
    { character: '突', unicode: '7A81', pinyin: 'tu¯', phrase: '突然', sentence: '他突然跳了起來。', image: 'tu_ran.jpg', translation: 'Sudden' },
    { character: '異', unicode: '7570', pinyin: 'yiˋ', phrase: '異常', sentence: '這個現象很異常。', image: 'yi_chang.jpg', translation: 'Different' },
    { character: '口', unicode: '53E3', pinyin: 'kouˇ', phrase: '口語', sentence: '他的口語很流利。', image: 'kou_yu.jpg', translation: 'Mouth' },
    { character: '興', unicode: '8208', pinyin: 'xing¯', phrase: '興趣', sentence: '他的興趣是畫畫。', image: 'xing_qu.jpg', translation: 'Interest' },
    { character: '嘟', unicode: '561F', pinyin: 'du¯', phrase: '嘟嘴', sentence: '他不高興的嘟嘴。', image: 'du_nang.jpg', translation: 'Mutter' },
    { character: '嘴', unicode: '5634', pinyin: 'zuiˇ', phrase: '嘴巴', sentence: '他的嘴巴很大。', image: 'zui_ba.jpg', translation: 'Mouth' },
    { character: '怪', unicode: '602A', pinyin: 'guaiˋ', phrase: '奇怪', sentence: '這個現象很奇怪。', image: 'qi_guai.jpg', translation: 'Strange' },
    { character: '扇', unicode: '6247', pinyin: 'shanˇ', phrase: '扇子', sentence: '夏天用扇子很涼快。', image: 'shan_zi.jpg', translation: 'Fan' },
    { character: '立', unicode: '7ACB', pinyin: 'liˋ', phrase: '立刻', sentence: '他立刻站了起來。', image: 'li_ke.jpg', translation: 'Stand' },
    { character: '刻', unicode: '523B', pinyin: 'ke¯', phrase: '刻意', sentence: '他刻意練習鋼琴。', image: 'ke_yi.jpg', translation: 'Moment' },
    { character: '閒', unicode: '9592', pinyin: 'xianˊ', phrase: '閒暇', sentence: '他在閒暇時間讀書。', image: 'xian_xia.jpg', translation: 'Idle' },
    { character: '慌', unicode: '614C', pinyin: 'huang¯', phrase: '慌亂', sentence: '他顯得很慌亂。', image: 'huang_luan.jpg', translation: 'Panic' },
    { character: '闖', unicode: '95D6', pinyin: 'chuangˇ', phrase: '闖禍', sentence: '他闖了大禍。', image: 'chuang_huo.jpg', translation: 'Rush' },
    { character: '仔', unicode: '4ED4', pinyin: 'ziˇ', phrase: '牛仔', sentence: '胡迪是一位西部牛仔。', image: 'xiao_zi.jpg', translation: 'Boy' },
    { character: '變', unicode: '8B8A', pinyin: 'bianˋ', phrase: '變化', sentence: '天氣有很大的變化。', image: 'bian_hua.jpg', translation: 'Change' },
    { character: '主', unicode: '4E3B', pinyin: 'zhuˇ', phrase: '主要', sentence: '這是主要的問題。', image: 'zhu_yao.jpg', translation: 'Main' },
    { character: '播', unicode: '64AD', pinyin: 'bo¯', phrase: '播種', sentence: '農民在播種。', image: 'bo_zhong.jpg', translation: 'Broadcast' },
    { character: '報', unicode: '5831', pinyin: 'baoˋ', phrase: '報紙', sentence: '他每天讀報紙。', image: 'bao_zhi.jpg', translation: 'Report' },
    { character: '力', unicode: '529B', pinyin: 'liˋ', phrase: '力量', sentence: '他的力量很大。', image: 'li_liang.jpg', translation: 'Power' },
    { character: '竟', unicode: '7ADF', pinyin: 'jingˋ', phrase: '竟然', sentence: '他竟然沒來。', image: 'jing_ran.jpg', translation: 'Actually' },
    { character: '巴', unicode: '5DF4', pinyin: 'ba¯', phrase: '嘴巴', sentence: '他的嘴巴很大。', image: 'zui_ba.jpg', translation: 'Hope' },
    { character: '底', unicode: '5E95', pinyin: 'diˇ', phrase: '底部', sentence: '杯子的底部有水。', image: 'di_bu.jpg', translation: 'Bottom' },
    { character: '妖', unicode: '5996', pinyin: 'yao¯', phrase: '妖怪', sentence: '他們在講妖怪故事。', image: 'yao_guai.jpg', translation: 'Demon' },
    { character: '擠', unicode: '64E0', pinyin: 'jiˇ', phrase: '擠壓', sentence: '他擠壓著牙膏。', image: 'ji_ya.jpg', translation: 'Squeeze' },
    { character: '鵝', unicode: '9D5D', pinyin: 'eˊ', phrase: '白鵝', sentence: '湖邊有很多白鵝。', image: 'bai_e.jpg', translation: 'Goose' },
    { character: '念', unicode: '5FF5', pinyin: 'nianˋ', phrase: '思念', sentence: '她在思念家人。', image: 'si_nian.jpg', translation: 'Miss' },
    { character: '曲', unicode: '66F2', pinyin: 'quˇ', phrase: '曲子', sentence: '這首曲子很好聽。', image: 'qu_zi.jpg', translation: 'Tune' },
    { character: '項', unicode: '9805', pinyin: 'xiangˋ', phrase: '項目', sentence: '這是一個重要的項目。', image: 'xiang_mu.jpg', translation: 'Item' },
    { character: '歌', unicode: '6B4C', pinyin: 'ge¯', phrase: '歌曲', sentence: '這是一首美妙的歌曲。', image: 'ge_qu.jpg', translation: 'Song' },
    { character: '浮', unicode: '6D6E', pinyin: 'fuˊ', phrase: '浮力', sentence: '木頭在水中有浮力。', image: 'fu_li.jpg', translation: 'Float' },
    { character: '掌', unicode: '638C', pinyin: 'zhangˇ', phrase: '手掌', sentence: '他的手掌很大。', image: 'shou_zhang.jpg', translation: 'Palm' },
    { character: '撥', unicode: '64A5', pinyin: 'bo¯', phrase: '撥動', sentence: '他撥動了琴弦。', image: 'bo_dong.jpg', translation: 'Dial' },
    { character: '波', unicode: '6CE2', pinyin: 'bo¯', phrase: '波浪', sentence: '海邊的波浪很大。', image: 'bo_lang.jpg', translation: 'Wave' },
    { character: '詩', unicode: '8A69', pinyin: 'shi¯', phrase: '詩歌', sentence: '他喜歡寫詩歌。', image: 'shi_ge.jpg', translation: 'Poem' },
    { character: '首', unicode: '9996', pinyin: 'shouˇ', phrase: '首歌', sentence: '這是一首動聽的歌。', image: 'shou_ge.jpg', translation: 'First' },
    { character: '脖', unicode: '8116', pinyin: 'boˊ', phrase: '脖子', sentence: '他的脖子很長。', image: 'bo_zi.jpg', translation: 'Neck' },
    { character: '唱', unicode: '5531', pinyin: 'changˋ', phrase: '唱歌', sentence: '她喜歡唱歌。', image: 'chang_ge.jpg', translation: 'Sing' },
    { character: '體', unicode: '9AD4', pinyin: 'tiˇ', phrase: '身體', sentence: '他的身體很健康。', image: 'shen_ti.jpg', translation: 'Body' },
    { character: '隻', unicode: '96BB', pinyin: 'zhi¯', phrase: '一隻', sentence: '這是一隻小貓。', image: 'yi_zhi_xiao_mao.jpg', translation: 'Measure word for animals' },
    { character: '翻', unicode: '7FFB', pinyin: 'fan¯', phrase: '翻頁', sentence: '請翻到下一頁。', image: 'fan_ye.jpg', translation: 'Flip' },
    { character: '倒', unicode: '5012', pinyin: 'daoˇ', phrase: '倒水', sentence: '請幫我倒點水。', image: 'dao_shui.jpg', translation: 'Pour' },
    { character: '肚', unicode: '809A', pinyin: 'duˇ', phrase: '肚子', sentence: '他說他的肚子疼。', image: 'du_zi.jpg', translation: 'Belly' },
    { character: '詠', unicode: '8A60', pinyin: 'yongˇ', phrase: '詠唱', sentence: '他們在詠唱詩歌。', image: 'yong_chang.jpg', translation: 'Chant' },
    { character: '駱', unicode: '99F1', pinyin: 'luoˋ', phrase: '駱駝', sentence: '駱駝在沙漠中行走。', image: 'luo_tuo.jpg', translation: 'Camel' },
    { character: '賓', unicode: '8CD3', pinyin: 'bin¯', phrase: '賓客', sentence: '他是我們的貴賓。', image: 'bin_ke.jpg', translation: 'Guest' },
    { character: '歲', unicode: '6B72', pinyin: 'suiˋ', phrase: '歲月', sentence: '歲月不饒人。', image: 'sui_yue.jpg', translation: 'Year' }
];


export const thirdGrade = [
];

export const fourthGrade = [

];

export const fifthGrade = [

];

export const sixthGrade = [

];
